### ISSUE TITLE
kwh berechnen und fortlaufend speichern

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.sourceanalytix#1]
Laut Vorgabe https://forum.iobroker.net/viewtopic.php?t=19643#p205253

Wenn man nur die Leistung zur Verfügung hat, muß man integrieren.

**Comment by DutchmanNL** [comment]
enhancement rejected, please use ioBroker.statistics to count/calculate pulse to units by hour.
This datapoint can be used for SourceAnalytix to calculate statistics.

**Comment by DutchmanNL** [comment]
enhancement reopend I think it is relevant to have this functionality in Source nalytix, feel free to vote (thumb up) to give me an idea what priority it should have

**Comment by kueppert** [comment]
Plus 1 von mir, wenn man damit dann den aktuellen Verbrauch in Watt der tuya Stecker in kWh umrechnen und protokollieren kann :)

**Comment by DutchmanNL** [comment]
> Plus 1 von mir, wenn man damit dann den aktuellen Verbrauch in Watt der tuya Stecker in kWh umrechnen und protokollieren kann :)

hup genau das wird damit möglich sein, es ist mir nur nicht klar wie es genau berechnet werden muss.

Also es gibt da 2 Baustellen, counter und W nach Wh, man muss sich aber im klaren sein das diese Berechnungen wen Daten hapern nicht 100% sind (leider) aber da kan ich dan leider auch net soviel daran machen :/

**Comment by kueppert** [comment]
Ja, das Thema wegen Ungenauigkeit ist mir bewusst. Mit dem anderen Adapter geht es leider nicht (oder ich weiß nicht, wie).
Danke dir auf jeden Fall. Wollte tuya schon mit tasmota flashen...

**Comment by DutchmanNL** [comment]
implemented version 0.2.81 ! have FUN !
