### ISSUE TITLE
final version planned respectively still in maintenance?

### ISSUE THREAD

**Issue by HGlab01** [iobroker-community-adapters/ioBroker.sourceanalytix#100]
Is there a plan to release a final version?
Is it planned to maintain this cool adapter in the future?
I would like to use it and ensure that is still an active project.

**Comment by Omega236** [comment]
I also hope that it will be developed further

**Comment by DutchmanNL** [comment]
Yes, Yes and YEeeeesssss !
Improvements are currently in development and will be released soon, that will be also the moment to move this adapter into the stable state !

**Comment by HGlab01** [comment]
Cool!
