### ISSUE TITLE
Gaszähler

### ISSUE THREAD

**Issue by Alveran81** [iobroker-community-adapters/ioBroker.sourceanalytix#102]
Hallo,
ich lese den Gaszähler über einen Readkontakt ein. Immer wenn er über die Null dreht wird ein Impuls gezählt. Daraus ergibt sich das 100 Impulese entsprechend 1m³ sind.
Dementsprechend ergibt sich natürlich im Adapter ein Kommafehler da hier mit 1000 Liter pro 1m³ gerechnet wird.
Gibt es die Möglichkeit bitte noch die Dezimeter Rechnung mit zu implementieren? Also 100 Kubikdezimeter sind 1 m³.

**Comment by DutchmanNL** [comment]
Ich verstehe das problem nicht ganz, 100 Impulse sind 1m3 .... wen man einen Datenpunkt hat wo dieser m3 wert landet kan man den doch loggen ?

Mit 0.4.7 haben ich die Möglichkeit eingebaut das man selber die unit wählt wo nach gerechnet werden soll egal welche unit die eingäbe ist.
<img width="766" alt="Schermafbeelding 2020-09-10 om 09 35 21" src="https://user-images.githubusercontent.com/7318445/92695588-f6153000-f348-11ea-89cb-de56e1564856.png">

Denke mal das sollt dan so passen, oder übersehe ich etwas ?
