### ISSUE TITLE
Heavy overload of raspberry pi 4 caused by sourceanalytix

### ISSUE THREAD

**Issue by jobohrer** [iobroker-community-adapters/ioBroker.sourceanalytix#109]
My setup is: Iobroker on a Raspberry Pi 4 with 2 GB  with Node.js  v10.18.0  NPM 6.13.4 (all up to date)  on SSD with 100GB free space. The SQL is run by MySQL. 
I installed sourceanalytix 2 weeks ago and needed it for only 4 objects.  Now comes the catch: roughly 1 min after activating the adapter the CPU load shoots up to 2.something. Then it goes down periodically but most of the time the reactivity of iobroker is so slow, that I'm compelled to take sourceanalytix down. Is this an expected behaviour?

**Comment by jobohrer** [comment]
I must admit, that this phanomen is not totally reproducible. The other day I could not write blockly script when sourceanalytics was active. And the ssh Window with linux top gave me roundabout 100% load for iobroker.+ . Every time I took sourceanalytics down, so went the load down. 
Now just as I write here, I started sourceanalytix and watched the ssh window. Guess what? Since 10 miinutes everything's roses. Maybe it's a clash of unknown other factors.

**Comment by jobohrer** [comment]
I have to beg your pardon. The culprit is not sourceanalytix, but a bad timing from a sensor to javascript. What I learned: Dont poll slow sensors with high rates.

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.

ich habe den code komplett redesigned und alle Berechnungen/Zugriffe auf den  Speicher verlegt

**Comment by DutchmanNL** [comment]
> I have to beg your pardon. The culprit is not sourceanalytix, but a bad timing from a sensor to javascript. What I learned: Dont poll slow sensors with high rates.

still SA caused an overload of IO,  I redesigned the code to move all calculations to the memory
