### ISSUE TITLE
Seit dem Jahreswechsel kann ich keine Startdaten mehr eingeben

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.sourceanalytix#110]
Habe den Adapter seit September laufen. Zu beginn habe ich die start-values eingegeben. Seit dem Jahreswechsel sind die Daten nicht mehr überall eintragbar:
![grafik](https://user-images.githubusercontent.com/34395245/72667045-03775600-3a18-11ea-9225-dc783b7b8bc2.png)

Warum sie raus sind, weiss ich natürlich auch nicht:
![grafik](https://user-images.githubusercontent.com/34395245/72667062-20138e00-3a18-11ea-8af8-9a5d76249c31.png)

Sieht etwas komisch aus...

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
