### ISSUE TITLE
Gesamtwert 2019 erzeugen

### ISSUE THREAD

**Issue by Easyrunner** [iobroker-community-adapters/ioBroker.sourceanalytix#112]
Um Gesamtwerte für das vergangene Jahr 2019 zu erhalten bitte die Wochen oder Monatswerte aus 2019 addieren und als Datenpunkt schreiben.

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.

es werde ab jetzt Datenpunkte pro Jahr erzeugt
