### ISSUE TITLE
Error in case handling of cost type identificaton : undefined

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.sourceanalytix#116]
**Discovergy Zähler RAW**
---------------------------
{
  "type": "state",
  "common": {
    "name": "Zählerstand Bezug Gesamt",
    "type": "number",
    "role": "value.power.consumption",
    "unit": "kWh",
    "write": false,
    "custom": {
      "sourceanalytix.0": {
        "enabled": true,
        "alias": "",
        "state_type": "kWh_consumption",
        "state_unit": "automatically",
        "costs": false,
        "consumption": true,
        "meter_values": true,
        "start_day": 1761.4692756,
        "start_week": 1691.7386039,
        "start_month": 1645.5787471,
        "start_quarter": 1008.8171379,
        "start_year": 1008.8171379
      }
    }
  },
  "native": {},
  "from": "system.adapter.discovergy.0",
  "user": "system.user.admin",
  "ts": 1581066049110,
  "_id": "discovergy.0.61228938.energy",
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**gosund SP1 RAW**
---------------------------
{
  "_id": "sonoff.0.3D-Drucker.ENERGY_Total",
  "common": {
    "type": "number",
    "role": "value.power.consumption",
    "read": true,
    "write": false,
    "unit": "kWh",
    "name": "3D-Drucker ENERGY  Total",
    "custom": {
      "sourceanalytix.0": {
        "start_day": 220.739,
        "enabled": true,
        "alias": "",
        "state_type": "kWh_consumption",
        "state_unit": "automatically",
        "costs": false,
        "consumption": false,
        "meter_values": false,
        "start_week": 0,
        "start_month": 0,
        "start_quarter": 0,
        "start_year": 0
      }
    }
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1580770800024,
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**gosund SP1 RAW**
---------------------------
{
  "_id": "sonoff.0.Spülmaschine.ENERGY_Total",
  "common": {
    "type": "number",
    "role": "value.power.consumption",
    "read": true,
    "write": false,
    "unit": "kWh",
    "name": "Spülmaschine ENERGY  Total",
    "custom": {
      "sourceanalytix.0": {
        "start_day": 438.699,
        "enabled": true,
        "alias": "",
        "state_type": "kWh_consumption",
        "state_unit": "automatically",
        "costs": false,
        "consumption": false,
        "meter_values": false,
        "start_week": 0,
        "start_month": 0,
        "start_quarter": 0,
        "start_year": 0
      }
    }
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1580770800024,
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**gosund SP1 RAW**
---------------------------
{
  "_id": "sonoff.0.Trockner.ENERGY_Total",
  "common": {
    "type": "number",
    "role": "value.power.consumption",
    "read": true,
    "write": false,
    "unit": "kWh",
    "name": "Trockner ENERGY  Total",
    "custom": {
      "sourceanalytix.0": {
        "start_day": 465.61,
        "enabled": true,
        "alias": "",
        "state_type": "kWh_consumption",
        "state_unit": "automatically",
        "costs": false,
        "consumption": false,
        "meter_values": false,
        "start_week": 0,
        "start_month": 0,
        "start_quarter": 0,
        "start_year": 0
      }
    }
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1580770800024,
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**gosund SP1 RAW**
---------------------------
{
  "_id": "sonoff.0.Waschmaschine.ENERGY_Total",
  "common": {
    "type": "number",
    "role": "value.power.consumption",
    "read": true,
    "write": false,
    "unit": "kWh",
    "name": "Waschmaschine ENERGY  Total",
    "custom": {
      "sourceanalytix.0": {
        "start_day": 535.732,
        "enabled": true,
        "alias": "",
        "state_type": "kWh_consumption",
        "state_unit": "automatically",
        "costs": false,
        "consumption": false,
        "meter_values": false,
        "start_week": 0,
        "start_month": 0,
        "start_quarter": 0,
        "start_year": 0
      }
    }
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1580770800024,
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
