### ISSUE TITLE
Kostenberechnung für Hoch und Niedertariff

### ISSUE THREAD

**Issue by massimo1971** [iobroker-community-adapters/ioBroker.sourceanalytix#119]
Wir haben bei uns 2 Tariffe, Hoch und Niedertariff.

Es wäre toll wenn ich die Zeit für die Tariffe hinterlegen könnte. Diese sind wie folgt:

-Von 07.00 bis 20.00 ist Hochtariff, danach Niedertariff.
-Samstag von 07.00 – 12.00 Hochtrariff
-Sonntag Niedertariff

Vielen Dank

**Comment by DutchmanNL** [comment]
der adapter bietet die Möglichkeit verschiedene Tarife zu Berechnung, die Datenpunkten dafür sollten anwesend sein eventuell per script (für zeit) getrennt.
