### ISSUE TITLE
DP Erzeugung trotz deaktiviertem Einstellungs TAB

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.sourceanalytix#120]
Wenn sich bei den jeweiligen Geräte Einstellungen, unter "Zählerwerte", Zahlen in den Feldern befinden, die >0 sind, werden durch Sourceanalytix auch dann Datenpunkte angelegt, wenn Sourecanalytix für dieses Gerät gar nicht mehr aktiviert ist.

Sie auch ioBroker Forum ab Beitrag #920 - #924
[https://forum.iobroker.net/topic/17187/test-adapter-sourceanalytix-v0-2-x/920#](url)

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.
