### ISSUE TITLE
states ausblenden bei nicht Verwendung

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.sourceanalytix#128]
Bei nicht verwenden einzelner Auswertungen, z.b Quarter, die entsprechenden states ausblenden(04_current_quarter)

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
