### ISSUE TITLE
Script Engine

### ISSUE THREAD

**Issue by skvarel** [iobroker-community-adapters/ioBroker.sourceanalytix#133]
Mit dem Update auf 0.4.0/0.4.1 macht meine Script Engine Probleme. Blockly Scripte lassen sich nicht mehr bearbeiten bzw. speichern. Bei Speichern werden Teile im Blockly entfernt.

Mit der 0.3.0 läuft alles gut!

JS Controler: 2.2.10
Script Engine: 4.4.3

**Comment by DutchmanNL** [comment]
hmm könntest du bitte mal debug console ausführen im browser was da passiert ?

es wuerde mich Sehr wundern wen das an SA liegt den der macht nix mit javascript....

**Comment by guergen1** [comment]
Im Debugmode des Firefox passiert nix...

**Comment by DutchmanNL** [comment]
inch kann es leider nirgendwo reproduzieren und wuerde mich freuen wen wir mal zusammen drüber schauen könnten eventuell per Webex ?

**Comment by DutchmanNL** [comment]
solved by updating javascript adapter
