### ISSUE TITLE
Warn Meldung nach js-controller Test 3.0.6

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.sourceanalytix#134]
V 0.4.1

Hallo, nach update des js-controller auf V 3.0.6 kommt das :

`sourceanalytix.0 2020-04-12 09:34:30.486 warn (34788) Object hm-rpc__0__NEQ1662322__2__ENERGY_COUNTER.2020.meterReadings.weeks.32 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number" sourceanalytix.0 2020-04-12 09:34:30.483 warn (34788) This object will not be created in future versions. Please report this to the developer.`

**Comment by DutchmanNL** [comment]
Danke ! das ist ein falsche positive ich muss mal analysieren wo das herkommt.
den die werte darin sind Nummern also macht es keinen sinn da ein object oder string draus zu machen :/

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/ec2dc5cd5b5ed585b9ffa71196cce0c62da34ea6#diff-7a9076d6d94e62c13d641aa71f19ae8eR219
