### ISSUE TITLE
THIS WEEK

### ISSUE THREAD

**Issue by skvarel** [iobroker-community-adapters/ioBroker.sourceanalytix#135]
Bitte wieder die Datenpunkte/Werte für die aktuelle Woche hinzufügen.

![grafik](https://user-images.githubusercontent.com/1114419/79076891-92d19400-7cfd-11ea-9a75-94b5df34b040.png)

**Comment by DennisXK** [comment]
Habe gerade den Adapter installiert und bei mir werden die einzeln Tage der Woche nicht angezeigt!

Was habe ich falsch gemacht? In den Adapter Einstellungen habe ich Tage, Wochen und Monate ausgewählt.

**Comment by moeff** [comment]
Hi, selbes Problem hier. In welcher Version waren die "THIS WEEK" denn vorhanden?

**Comment by DutchmanNL** [comment]
these values were present in previous version but removed, there are 2 options for implementing it : 

1 (in progress) : implement periods which will allow going back like 7 days
2 (not requeted) : implement same structure back again based on weekdays

Is going back by periods for 7 days sufficient or do we need special datapoint for the week-days

If yes, should they reset at week start or keep the values from previous week

**Comment by DutchmanNL** [comment]
0.4.8-beta.0 release, und das gibts wieder ein current year und auch diese Woche :)

![Schermafbeelding 2020-10-06 om 16 38 40](https://user-images.githubusercontent.com/7318445/95219384-9a2db200-07f5-11eb-9815-5b0bcb7ad049.png)
