### ISSUE TITLE
Enable choosing values without unit

### ISSUE THREAD

**Issue by baeriwiliwonka** [iobroker-community-adapters/ioBroker.sourceanalytix#136]
Many users do have Tasmota to read measurement values. In standard setup it does not deliver units via MQTT.
To use sourceanalalytics the unit must be available in the Object which needs to be added manually then.
Would be nice, when the unit is no precondition and the standardunit would be used, e.g. kWh for the power consuption.

Thanks!

**Comment by DutchmanNL** [comment]
fixed in 0.4.5 please try, unit completely configurable now

**Comment by baeriwiliwonka** [comment]
works fine, thanks!
