### ISSUE TITLE
Show comsuption/costs of last day(s)

### ISSUE THREAD

**Issue by baeriwiliwonka** [iobroker-community-adapters/ioBroker.sourceanalytix#137]
At the moment only the values for completed weeks are visible.
On day basis it's only possible to see the current day.

Would be nice to see at least the consuption/costs of the last day to make a compairson on day basis.
For me a new Object for "last day" in the readings and also in the costs would be enough.

Thanks in advance!!

**Comment by DutchmanNL** [comment]
relations to https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/issues/135
