### ISSUE TITLE
Datenpunkte stehen an falscher Stelle

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.sourceanalytix#138]
Folgende DP sollten nicht unter dem Jahr, sondern besser unter dem Gerät selbst stehen, es ist zwar noch ein wenig Zeit bis zum Jahreswechsel, aber die Werte müssten dann jedes Jahr (z.B. im VIS) umgestellt werden.
![grafik](https://user-images.githubusercontent.com/34395245/79122843-112f4400-7d99-11ea-8e03-cbdaddb6e11c.png)

**Comment by guergen1** [comment]
Die Verbräuche ebenso!

**Comment by DutchmanNL** [comment]
work as design die total werte stehen unter der cathegorie ab jetzt, Gegenvorschlag ?

**Comment by guergen1** [comment]
Es geht doch um die current-Werte, die stehen unter 2020. Es wäre doch besser, wenn diese Werte 2 Ebenen höher stehen würden. Im Jahr 2021 müssen dann diverse VIS umgebaut werden

**Comment by guergen1** [comment]
Die Total-Werte können da ja auch stehen😉

**Comment by Knallochse** [comment]
Wie schon im Forum erwähnt https://forum.iobroker.net/post/411940

mein Vorschlag:
Wie wäre es mit einem Ordner „current Year“ in dem die aktuellen Jahreszahlen enthalten sind.
Erst am Jahresende (31.12.2020, 31.12.2021 usw.) werden die Zahlen in den Ordner 2020, 2021 usw. abgelegt.

**Comment by fastsonic** [comment]
current Year würde mich auch sehr freuen . Ich tracke einen Teil der Punkte in die Influxdb und von da aus weiter nach Grafana. Wenn sich die Datenpunktnamen ändern, muss ich sie neu  anlegen. dann haben sie einen neuen Namen in der InfluxDB und müssen in Grafana wieder angepasst werden.

**Comment by Knallochse** [comment]
Da gerade am Adapter gearbeitet wird, wollte ich fragen ob sich an der Struktur der Datenpunkte noch was ändert.
Im jetzigen Zustand müsste man z.Bsp. In der VIS jedes Jahr die Datenpunkte anpassen um die aktuellen Jahrsdaten angezeigt zu bekommen.

**Comment by DutchmanNL** [comment]
hmm, es war ein feature request es auf Jahre zu unterteilen. In vis könnte man nen replace all machen

**Comment by Knallochse** [comment]
Ich finde es Prinzipiell sinnvoll, die Daten nach Jahren aufzuteilen.
Mein Änderungsvorschlag : https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/issues/138#issuecomment-613303646

**Comment by DutchmanNL** [comment]
Hatte ich auch mal drüber nachgedacht, jedoch davon abgesehen den Risiko bei Jahres wechsel zu gross das ne copy action schief geht und dan hat man kompletten Daten Brei 

Fuer die anzeige in VIS und dergleichen waehre eventuell der enhancement das laufende jähr in HTML oder JSON ab zu speichern ne idee ?

Parallel schreiben würde auch gehen aber extra Belastung.
Code technisch werde ich das Risiko mit copy zum Jahreswechsel nicht machen

**Comment by Knallochse** [comment]
Wenn ich dich richtig verstanden habe, dann möchtest du einen zusätzlichen Datenpunkt einführen (Current Yaer), welcher die Daten des aktuellen Jahres enthält. Also eine Art exakte Kopie des aktuellen Jahres. 
Klar, das wäre genau so hilfreich. Hauptsache man muss nicht jedes Jahr die Datenpunkte in der VIS anpassen.
Ich **vermute** , dass die meisten User an den aktuellen Jahres/Quartal/Monat/Wochen Verbrauch interessiert sind.

**Comment by DutchmanNL** [comment]
> Ich **vermute** , dass die meisten User an den aktuellen Jahres/Quartal/Monat/Wochen Verbrauch interessiert sind.

mja da gibt es halt unterschiedliche Meinung zu die historische Aufzeichnung war ein wünsch fuer die jähre... ich lass mir das mal durch Adenkopf gehen

**Comment by Knallochse** [comment]
Ich möchte ergänzen, dass es **keine** Aufforderung zur Änderung deines Adapters ist.

_Ich bin dir sehr Dankbar für deine Arbeit._

**Comment by DutchmanNL** [comment]
> Ich möchte ergänzen, dass es **keine** Aufforderung zur Änderung deines Adapters ist.
> 
> _Ich bin dir sehr Dankbar für deine Arbeit._

alles gut :) muss nur irgendwie ne Kombi finden wo wir alle zufrieden sind

**Comment by fastsonic** [comment]
Ich möchte auch nochmal sagen das ich mehr als Dankbar bin für den Adapter. 
Vieleicht gibt es ja noch eine gute Idee wie ich damit klar komme das sich die Ordner jedes Jahr ändern.

Mein Problem ist einfach das alles weiter in die InfluxDB läuft und von da an Grafana. Bei einem Jahreswechsel bekomm ich halt neue Datenbanken in der Influx und müsste alles umstellen.
Ich denke halt wenn man das ganze nochmal in ein Current Year kopieren würde wären doch alle zufrieden ? 

Dann können die einen mit den Jahreszahlen arbeiten und die anderen mit current year.
So hab ich mir das gerade eingerichtet und muss nur am Ende Pünklich dran denken den copy auf die neue Jahreszahl zu ändern.
By the way:
last Day, week und month würde ich mir aber wirklich bald wünschen :)
Gruß

**Comment by DutchmanNL** [comment]
> Ich möchte auch nochmal sagen das ich mehr als Dankbar bin für den Adapter.

Danke :) 

> last Day, week und month würde ich mir aber wirklich bald wünschen :)

Den habe wir so noch nicht als Enhancementt issue, Perioden ja (x tage/woche usw) und auch diese Woche aber nicht last xxx 

ist das was du suchst ? https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/issues/135
Sonst bitte seperates issue fuer diese Datenpunkte

**Comment by fastsonic** [comment]
Hi,
nein ich dachte wirklich an last day last week. Aber dann realisiere ich das über Scripts. ( nicht wirchtig) 
Aber deswegen würde ich mir Current Year Wünschen damit die Scripte richtig laufen. Weil als Quelle kann ich dann immer Current angeben und zu Last kopieren.
Danke

**Comment by DutchmanNL** [comment]
> Weil als Quelle kann ich dann immer Current angeben und zu Last kopieren.

kannst in script mit variable jähr arbeiten dan adoptiert sich das ja automatisch ;0

**Comment by fastsonic** [comment]
Hier ja. Und auch für Current Jear can ich ein Script schreiben das mir Current Year erstellt so das die Influxdb und Grafana hintendran auch wieder laufen.
Aber wenn der Ordner schon von Sourceanalytics selber erstellt würde könnte ich mir viel ausenrum sparen. Du musst einfach nur sagen ob du es machst oder nicht damit ich weiß ob ich mir was ausenrum baue oder nicht.
Ich würde mich ärgern wenn ich mir lauter sachen ausenrum baue ( kleiner noop) und du es dann integrierst ;)
Brauch da etwas länger zum bauen als Anfänger.

**Comment by DutchmanNL** [comment]
@fastsonic ich überlege gerade wie wir es am besten angehen .... den Ordner erstellen is kein problem, die frage lautest welche werte sollen da rein.

Beispiel alles was als Woche/monate usw geloggt wird wuerde ich beim jahr behalten.
Welche werte sind interessant fuer die visu ?

**Comment by fastsonic** [comment]
Ich kann jetzt nur für mich sprechen und kenne es halt aus der alten Version.
Darauf habe ich meine Sachen aufgebaut.
Mag auch sein das ich mich einfach neu organisieren muss und mich besser einlesen muss um meine Probleme zu lösen !?

Wegen current Year.
ich logge einen Teil der Werte in die Influxdb über IOBroker, damit ich verläufe habe über die letzten Tage das geht über die Jahre drüber. Also z.B. letzen 9 Monate oder die letzen 24 Monate.
Aktuell ist es ja so das ein Datenpunkt in Influx, mit der Jahreszahl erstellt wird. Bei Jahreswechsel funktioniert also die letzten 3 Monate nicht. 
Sind dann auch nicht die über IOBroker->Objects->schraubenschlüssel-> in Influx loggen" weg ? 
Datenpunkt in Influx ändert sich ja. Somit ist mein Verlauf weg und ich muß den neuen Datenpunkt verarbeiten, Oder mir mit Scripten die Datenpunkte in neue Datenpunkte schreiben die sich nicht ändern vom Pfad.
Im grunde brauch ( Ich) für langzeit Graphen, Verläufe, Vergleiche:
Current Day, Week,month,Year und Last Day,Week,month,year.
Datenpunkte immer im selben Pfad.
Damit kann ich alles ohne scripte von meiner Seite in der Datenbank, Grafana, Kostenübersichten, auswerten und anzeigen lassen.

**Comment by DutchmanNL** [comment]
Also würde es reichen nur die current unter current_year an zu legen

Also current day, week usw ?

**Comment by fastsonic** [comment]
Für mich gesehen würde mir das reichen. Für andere wären vieleicht die anderen Werte auch interessant Januar Februar....
Kannst du vom Programm nicht vieleicht einfach einen automatischen ( Current Year Link ) erstellen der dann von der Baumstruktur einfach auf das aktuelle Jahr zeigt. So würde von der Baumstruktur das zwar doppelt sein aber die Werte müssten nicht doppelt gespeichert werden ?
Für die "Last" Werte würde das auf jedenfall reichen. da macht jeweils nur das letzte Sinn.

**Comment by DutchmanNL** [comment]
mein Vorschlag währe dan es soo zu machen

![Uploading Schermafbeelding 2020-09-22 om 19.33.33.png…]()

**Comment by guergen1** [comment]
Currend year find ich gut!

**Comment by Knallochse** [comment]
Damit wäre ich ebenfalls Happy 👍

**Comment by DutchmanNL** [comment]
na dan baue ich das heute Abend ein, tests local laufen schon sehr gut also erwartet mal ne neue beta :)

![Uploading Schermafbeelding 2020-09-23 om 11.28.10.png…]()

**Comment by fastsonic** [comment]
Danke. Ja das finde ich auch gut ! 
Paypal hab ich dir dafür was rübergeschickt.

**Comment by DutchmanNL** [comment]
> Danke. Ja das finde ich auch gut !
> Paypal hab ich dir dafür was rübergeschickt.

Herzlichen dank fuer die Unterstützung !

**Comment by fastsonic** [comment]
Dein Adapter erleichtert mir die Arbeit und deine Unterstützung hier ist auch klasse.
Ich und sicher viele anderen danken dir :+1:

**Comment by DutchmanNL** [comment]
kure frage noch : die Wochen werte (Mo-Fr) sollten aber am Woche Anfang immer wieder auf 0 springen oder ?
(könnte das auch konfigurabel machen, was meint ihr ?)

**Comment by fastsonic** [comment]
du meinst dann unter Current week...
Logisch macht das auf jedenfall Sinn. Wäre ja falsch wenn ein Wert erst mit einem neuen Überschrieben wird. 
In Last week swerden ja die alten Werte mit neuen überschrieben und durchlaufen keinen 0 Punkt richtig ?
Hier wäre es für das loggen doof wenn die Werte irgendwo erstmal auf 0 springen würden.

**Comment by Knallochse** [comment]
Ich bin auch der Meinung, dass diese 7 (Mo-So) Tageswerte unter Current Year am Anfang der Moche (Montags 0:00 Uhr) auf 0 gesellt werden sollten. Ein vermischen alter und neuer Werte unter Current wäre bestimmt sehr verwirrend.
Möchte hiermit ebenfalls meinen Respekt und meinen Dank für deinen Einsatz für das gesamte Projekt IoBroker zum Ausdruck bringen. Vielen Dank

**Comment by DutchmanNL** [comment]
danke leute, so machen wir es :)

bei Wochen Wechsel : 
- alle jetzigen Ma-Fr werte werden übernommen nach previous week
- alle Ma-Fr werden springen auf 0

Selbe fuer die andere previous, wen Wechsel wandert jetziger wert nach previous (und bleibt dort bist Nestes update)

**Comment by JBSullivan** [comment]
Warum nur Mo. - Fr.? Ist das nur eine Arbeitswoche - Mo.- So. wäre doch sinniger.

**Comment by DutchmanNL** [comment]
lol, selbstverständlich Mo-So sorry :)

**Comment by MMeinhardt1** [comment]
In den Niederlande gibt es kein Sa und So 😂

**Comment by DutchmanNL** [comment]
ich hoffe ihr habt Freude an dem was draus geworden ist, viel spass mit 0.4.8-beta.0 !

![Schermafbeelding 2020-10-06 om 16 38 40](https://user-images.githubusercontent.com/7318445/95219310-81bd9780-07f5-11eb-867f-b64f44be44b8.png)
