### ISSUE TITLE
Ordner "2020" wird nicht bei Parser Datenpunkt angelegt

### ISSUE THREAD

**Issue by Easyrunner** [iobroker-community-adapters/ioBroker.sourceanalytix#139]
Getestet unter Version 0.42 
wird bei einem Parser Datenpunkt kein Ordner "2020" angelegt.
![2020-04-14 15_43_26-objects - ioBroker](https://user-images.githubusercontent.com/47195199/79261635-7023b480-7e90-11ea-9da5-7cd0807674d7.jpg)

**Comment by DutchmanNL** [comment]
kommt eine Meldung im log ?

**Comment by Easyrunner** [comment]
Hier das Log
`sourceanalytix.0	2020-04-15 20:47:35.012	info	(508) Initialising mqtt.0.Wemos08-Flow.Flowmeter.Total with configuration {"stateDetails":{"alias":"","consumption":false,"costs":false,"deviceName":"mqtt__0__Wemos08-Flow__Flowmeter__Total","financie
sourceanalytix.0	2020-04-15 20:47:35.012	info	(508) Initialising (11 of 11) state mqtt.0.Wemos08-Flow.Flowmeter.Total
sourceanalytix.0	2020-04-15 20:47:35.012	info	(508) Initialization finished for : alias.0.smartmeter.zaehler1_haushalt.bezug_total
sourceanalytix.0	2020-04-15 20:47:35.011	info	(508) Meter Calculation executed consumed data for alias.0.smartmeter.zaehler1_haushalt.bezug_total : {"consumedDay":1.6,"consumedWeek":9.7,"consumedMonth":49.1,"consumedQuarter":49.1,"consumedYear":5
sourceanalytix.0	2020-04-15 20:47:35.008	info	(508) Set calculated value 1276.9 on state : alias__0__smartmeter__zaehler1_haushalt__bezug_total.Current_Reading}
sourceanalytix.0	2020-04-15 20:47:35.008	info	(508) Calculation for alias.0.smartmeter.zaehler1_haushalt.bezug_total with value : {"val":1276.9,"ack":true,"ts":1586976449800,"q":0,"from":"system.adapter.smartmeter.1","user":"system.user.admin","l
sourceanalytix.0	2020-04-15 20:47:35.007	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:47:20.728	info	(508) Meter Calculation executed consumed data for alias.0.smartmeter.zaehler0_Gesamt.bezug_total : {"consumedDay":2.3,"consumedWeek":16,"consumedMonth":67.3,"consumedQuarter":67.3,"consumedYear":135
sourceanalytix.0	2020-04-15 20:47:20.720	info	(508) Set calculated value 2990.9 on state : alias__0__smartmeter__zaehler0_Gesamt__bezug_total.Current_Reading}
sourceanalytix.0	2020-04-15 20:47:20.719	info	(508) Calculation for alias.0.smartmeter.zaehler0_Gesamt.bezug_total with value : {"val":2990.9,"ack":true,"ts":1586976440712,"q":0,"from":"system.adapter.smartmeter.0","user":"system.user.admin","lc
sourceanalytix.0	2020-04-15 20:47:20.231	info	(508) Initialising alias.0.smartmeter.zaehler1_haushalt.bezug_total with configuration {"stateDetails":{"alias":"","consumption":true,"costs":true,"deviceName":"alias__0__smartmeter__zaehler1_haushal
sourceanalytix.0	2020-04-15 20:47:20.230	info	(508) Initialising (10 of 11) state alias.0.smartmeter.zaehler1_haushalt.bezug_total
sourceanalytix.0	2020-04-15 20:47:20.229	info	(508) Initialization finished for : alias.0.smartmeter.zaehler0_Gesamt.bezug_total
sourceanalytix.0	2020-04-15 20:47:20.228	info	(508) Meter Calculation executed consumed data for alias.0.smartmeter.zaehler0_Gesamt.bezug_total : {"consumedDay":2.3,"consumedWeek":16,"consumedMonth":67.3,"consumedQuarter":67.3,"consumedYear":135
sourceanalytix.0	2020-04-15 20:47:20.221	info	(508) Set calculated value 2990.9 on state : alias__0__smartmeter__zaehler0_Gesamt__bezug_total.Current_Reading}
sourceanalytix.0	2020-04-15 20:47:20.220	info	(508) Calculation for alias.0.smartmeter.zaehler0_Gesamt.bezug_total with value : {"val":2990.9,"ack":true,"ts":1586976429814,"q":0,"from":"system.adapter.smartmeter.0","user":"system.user.admin","lc
sourceanalytix.0	2020-04-15 20:47:20.219	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:47:06.684	info	(508) Initialising alias.0.smartmeter.zaehler0_Gesamt.bezug_total with configuration {"stateDetails":{"alias":"","consumption":true,"costs":true,"deviceName":"alias__0__smartmeter__zaehler0_Gesamt__b
sourceanalytix.0	2020-04-15 20:47:06.684	info	(508) Initialising (9 of 11) state alias.0.smartmeter.zaehler0_Gesamt.bezug_total
sourceanalytix.0	2020-04-15 20:47:06.684	info	(508) Initialization finished for : alias.0.smartmeter.zaehler0_Gesamt.abgabe
sourceanalytix.0	2020-04-15 20:47:06.683	info	(508) Meter Calculation executed consumed data for alias.0.smartmeter.zaehler0_Gesamt.abgabe : {"consumedDay":40.3,"consumedWeek":90.1,"consumedMonth":506.2,"consumedQuarter":506.2,"consumedYear":126
sourceanalytix.0	2020-04-15 20:47:06.680	info	(508) Set calculated value 3679 on state : alias__0__smartmeter__zaehler0_Gesamt__abgabe.Current_Reading}
sourceanalytix.0	2020-04-15 20:47:06.679	info	(508) Calculation for alias.0.smartmeter.zaehler0_Gesamt.abgabe with value : {"val":3679,"ack":true,"ts":1586969815836,"q":0,"from":"system.adapter.smartmeter.0","user":"system.user.admin","lc":15869
sourceanalytix.0	2020-04-15 20:47:06.679	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:57.503	info	(508) Meter Calculation executed consumed data for hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER : {"consumedDay":0.529,"consumedWeek":4.289,"consumedMonth":30.018,"consumedQuarter":30.018,"consumedYear":60.6
sourceanalytix.0	2020-04-15 20:46:57.499	info	(508) Set calculated value 66.207399902 on state : hm-rpc__0__OEQ0947537__2__ENERGY_COUNTER.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:57.497	info	(508) Calculation for hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER with value : {"val":66207.399902,"ack":true,"ts":1586976417489,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":158697
sourceanalytix.0	2020-04-15 20:46:52.645	error	at processImmediate (timers.js:658:5)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at tryOnImmediate (timers.js:676:5)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at runCallback (timers.js:705:18)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4855:34)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at Sourceanalytix.emit (events.js:198:13)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at Sourceanalytix.onStateChange (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:418:11)
sourceanalytix.0	2020-04-15 20:46:52.645	error	at Sourceanalytix.calculationHandler (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:784:26)
sourceanalytix.0	2020-04-15 20:46:52.645	error	(508) [calculationHandler mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total] error: Cannot read property 'toLowerCase' of undefined, stack: TypeError: Cannot read property 'toLowerCase' of undefined
sourceanalytix.0	2020-04-15 20:46:52.642	info	(508) Calculation for mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total with value : {"val":7449,"ack":true,"ts":1586976412612,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1586
sourceanalytix.0	2020-04-15 20:46:51.388	info	(508) Initialising alias.0.smartmeter.zaehler0_Gesamt.abgabe with configuration {"stateDetails":{"alias":"","consumption":true,"costs":true,"deviceName":"alias__0__smartmeter__zaehler0_Gesamt__abgabe
sourceanalytix.0	2020-04-15 20:46:51.388	info	(508) Initialising (8 of 11) state alias.0.smartmeter.zaehler0_Gesamt.abgabe
sourceanalytix.0	2020-04-15 20:46:51.387	info	(508) Initialization finished for : javascript.0.PV.Heizungsstrom_Summe
sourceanalytix.0	2020-04-15 20:46:51.386	info	(508) Meter Calculation executed consumed data for javascript.0.PV.Heizungsstrom_Summe : {"consumedDay":0.6,"consumedWeek":6.2,"consumedMonth":18.2,"consumedQuarter":18.2,"consumedYear":845.3,"priceD
sourceanalytix.0	2020-04-15 20:46:51.379	info	(508) Set calculated value 1714 on state : javascript__0__PV__Heizungsstrom_Summe.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:51.378	info	(508) Calculation for javascript.0.PV.Heizungsstrom_Summe with value : {"val":1714,"ack":true,"ts":1586976233223,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15869727459
sourceanalytix.0	2020-04-15 20:46:51.377	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:37.901	info	(508) Initialising javascript.0.PV.Heizungsstrom_Summe with configuration {"stateDetails":{"alias":"Summe Heizungsstrom (Javascript)","consumption":true,"costs":true,"deviceName":"javascript__0__PV__
sourceanalytix.0	2020-04-15 20:46:37.901	info	(508) Initialising (7 of 11) state javascript.0.PV.Heizungsstrom_Summe
sourceanalytix.0	2020-04-15 20:46:37.901	info	(508) Initialization finished for : modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler
sourceanalytix.0	2020-04-15 20:46:37.900	info	(508) Meter Calculation executed consumed data for modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler : {"consumedDay":40.346,"consumedWeek":90.27,"consumedMonth":507.187,"consumedQuarter":507
sourceanalytix.0	2020-04-15 20:46:37.898	info	(508) Set calculated value 3685.007 on state : modbus__0__inputRegisters__30583_Zählerstand_Einspeisezähler.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:37.897	info	(508) Calculation for modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler with value : {"val":3685007,"ack":true,"ts":1586969818424,"q":0,"from":"system.adapter.modbus.0","user":"system.user.ad
sourceanalytix.0	2020-04-15 20:46:37.897	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:37.503	info	(508) Initialising modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler with configuration {"stateDetails":{"alias":"Netz-Einspeisung ","consumption":false,"costs":false,"deviceName":"modbus__0_
sourceanalytix.0	2020-04-15 20:46:37.503	info	(508) Initialising (6 of 11) state modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler
sourceanalytix.0	2020-04-15 20:46:37.502	info	(508) Initialization finished for : modbus.0.inputRegisters.30529_Gesamtertrag_Wh
sourceanalytix.0	2020-04-15 20:46:37.501	info	(508) Meter Calculation executed consumed data for modbus.0.inputRegisters.30529_Gesamtertrag_Wh : {"consumedDay":48.062,"consumedWeek":121.753,"consumedMonth":634.249,"consumedQuarter":634.249,"cons
sourceanalytix.0	2020-04-15 20:46:37.493	info	(508) Set calculated value 5093.522 on state : modbus__0__inputRegisters__30529_Gesamtertrag_Wh.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:37.491	info	(508) Calculation for modbus.0.inputRegisters.30529_Gesamtertrag_Wh with value : {"val":5093522,"ack":true,"ts":1586974467357,"q":0,"from":"system.adapter.modbus.0","user":"system.user.admin","lc":15
sourceanalytix.0	2020-04-15 20:46:37.489	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:27.461	info	(508) Initialising modbus.0.inputRegisters.30529_Gesamtertrag_Wh with configuration {"stateDetails":{"alias":"Gesamtertrag_PV_Wh_SMA","consumption":true,"costs":false,"deviceName":"modbus__0__inputRe
sourceanalytix.0	2020-04-15 20:46:27.460	info	(508) Initialising (5 of 11) state modbus.0.inputRegisters.30529_Gesamtertrag_Wh
sourceanalytix.0	2020-04-15 20:46:27.460	info	(508) Initialization finished for : modbus.0.inputRegisters.30531_Gesamtertrag_kWh
sourceanalytix.0	2020-04-15 20:46:27.460	info	(508) Meter Calculation executed consumed data for modbus.0.inputRegisters.30531_Gesamtertrag_kWh : {"consumedDay":49,"consumedWeek":122,"consumedMonth":635,"consumedQuarter":635,"consumedYear":1943,
sourceanalytix.0	2020-04-15 20:46:27.456	info	(508) Set calculated value 5094 on state : modbus__0__inputRegisters__30531_Gesamtertrag_kWh.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:27.455	info	(508) Calculation for modbus.0.inputRegisters.30531_Gesamtertrag_kWh with value : {"val":5094,"ack":true,"ts":1586973381136,"q":0,"from":"system.adapter.modbus.0","user":"system.user.admin","lc":1586
sourceanalytix.0	2020-04-15 20:46:27.454	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:18.453	info	(508) Initialising modbus.0.inputRegisters.30531_Gesamtertrag_kWh with configuration {"stateDetails":{"alias":"Gesamtertrag_kWh_PV_SMA","consumption":true,"costs":false,"deviceName":"modbus__0__input
sourceanalytix.0	2020-04-15 20:46:18.453	info	(508) Initialising (4 of 11) state modbus.0.inputRegisters.30531_Gesamtertrag_kWh
sourceanalytix.0	2020-04-15 20:46:18.452	info	(508) Initialization finished for : hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER
sourceanalytix.0	2020-04-15 20:46:18.452	info	(508) Meter Calculation executed consumed data for hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER : {"consumedDay":0.528,"consumedWeek":4.288,"consumedMonth":30.017,"consumedQuarter":30.017,"consumedYear":60.5
sourceanalytix.0	2020-04-15 20:46:18.445	info	(508) Set calculated value 66.206199951 on state : hm-rpc__0__OEQ0947537__2__ENERGY_COUNTER.Current_Reading}
sourceanalytix.0	2020-04-15 20:46:18.444	info	(508) Calculation for hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER with value : {"val":66206.199951,"ack":true,"ts":1586976270834,"q":0,"from":"system.adapter.hm-rpc.0","user":"system.user.admin","lc":158697
sourceanalytix.0	2020-04-15 20:46:18.443	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:46:03.414	info	(508) Initialising hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER with configuration {"stateDetails":{"alias":"Stromverbrauch Aussenanlage","consumption":true,"costs":true,"deviceName":"hm-rpc__0__OEQ0947537__
sourceanalytix.0	2020-04-15 20:46:03.413	info	(508) Initialising (3 of 11) state hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER
sourceanalytix.0	2020-04-15 20:46:03.413	info	(508) Initialization finished for : mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total
sourceanalytix.0	2020-04-15 20:46:03.411	error	at process._tickCallback (internal/process/next_tick.js:68:7)
sourceanalytix.0	2020-04-15 20:46:03.411	error	at Sourceanalytix.initialize (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:271:16)
sourceanalytix.0	2020-04-15 20:46:03.411	error	at Sourceanalytix.calculationHandler (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:784:26)
sourceanalytix.0	2020-04-15 20:46:03.411	error	(508) [calculationHandler mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total] error: Cannot read property 'toLowerCase' of undefined, stack: TypeError: Cannot read property 'toLowerCase' of undefined
sourceanalytix.0	2020-04-15 20:46:03.410	info	(508) Calculation for mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total with value : {"val":7449,"ack":true,"ts":1586976352942,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1586
sourceanalytix.0	2020-04-15 20:46:03.407	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:45:54.245	info	(508) Initialising mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total with configuration {"stateDetails":{"alias":"","consumption":true,"costs":false,"deviceName":"mqtt__0__Wemos12-Wasserzaehler__Wasse
sourceanalytix.0	2020-04-15 20:45:54.245	info	(508) Initialising (2 of 11) state mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total
sourceanalytix.0	2020-04-15 20:45:54.245	error	(508) Sorry unite type kWh not supported (yet), parser.0.Leistung_aufaddiert will be ignored from calculations!
sourceanalytix.0	2020-04-15 20:45:54.244	error	(508) Identifying unit failed, please ensure state has a propper unit assigned or the unit is manually choosen in state settings !
sourceanalytix.0	2020-04-15 20:45:54.243	info	(508) Initialising parser.0.Leistung_aufaddiert with configuration {"stateDetails":{"alias":"Solarthermie","consumption":true,"costs":true,"deviceName":"parser__0__Leistung_aufaddiert","financielCath
sourceanalytix.0	2020-04-15 20:45:54.241	info	(508) Initialising (1 of 11) state parser.0.Leistung_aufaddiert
sourceanalytix.0	2020-04-15 20:45:54.238	info	(508) for state alias.0.smartmeter.zaehler1_haushalt.bezug_total Previous watt calculated reading used Version > 4 from {"val":1273.4,"ack":true,"ts":1586872928382,"q":0,"from":"system.adapter.source
sourceanalytix.0	2020-04-15 20:45:54.236	info	(508) for state alias.0.smartmeter.zaehler0_Gesamt.bezug_total Previous watt calculated reading used Version > 4 from {"val":2986.3,"ack":true,"ts":1586872912948,"q":0,"from":"system.adapter.sourcean
sourceanalytix.0	2020-04-15 20:45:54.233	info	(508) for state alias.0.smartmeter.zaehler0_Gesamt.abgabe Previous watt calculated reading used Version > 4 from {"val":3633.9,"ack":true,"ts":1586874268954,"q":0,"from":"system.adapter.sourceanalyti
sourceanalytix.0	2020-04-15 20:45:54.231	info	(508) for state javascript.0.PV.Heizungsstrom_Summe Previous watt calculated reading used Version > 4 from {"val":1712.9,"ack":true,"ts":1586872885129,"q":0,"from":"system.adapter.sourceanalytix.0","
sourceanalytix.0	2020-04-15 20:45:54.229	info	(508) for state modbus.0.inputRegisters.30583_Zählerstand_Einspeisezähler Previous watt calculated reading used Version > 4 from {"val":3639.823,"ack":true,"ts":1586874282527,"q":0,"from":"system.ada
sourceanalytix.0	2020-04-15 20:45:54.226	info	(508) for state modbus.0.inputRegisters.30529_Gesamtertrag_Wh Previous watt calculated reading used Version > 4 from {"val":5036.186,"ack":true,"ts":1586874282459,"q":0,"from":"system.adapter.sourcea
sourceanalytix.0	2020-04-15 20:45:54.224	info	(508) for state modbus.0.inputRegisters.30531_Gesamtertrag_kWh Previous watt calculated reading used Version > 4 from {"val":5036,"ack":true,"ts":1586873866262,"q":0,"from":"system.adapter.sourceanal
sourceanalytix.0	2020-04-15 20:45:54.221	info	(508) for state hm-rpc.0.OEQ0947537.2.ENERGY_COUNTER Previous watt calculated reading used Version > 4 from {"val":65.433,"ack":true,"ts":1586874167617,"q":0,"from":"system.adapter.sourceanalytix.0",
sourceanalytix.0	2020-04-15 20:45:54.044	info	(508) Welcome to SourceAnalytix, making things ready ...
sourceanalytix.0	2020-04-15 20:45:54.004	info	(508) starting. Version 0.4.2 in /opt/iobroker/node_modules/iobroker.sourceanalytix, node: v10.19.0
`

**Comment by Easyrunner** [comment]
Hier das Log mit Fehler dazu:
`sourceanalytix.0	2020-04-15 20:46:03.411	error	at process._tickCallback (internal/process/next_tick.js:68:7)
sourceanalytix.0	2020-04-15 20:46:03.411	error	at Sourceanalytix.initialize (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:271:16)
sourceanalytix.0	2020-04-15 20:46:03.411	error	at Sourceanalytix.calculationHandler (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:784:26)
sourceanalytix.0	2020-04-15 20:46:03.411	error	(508) [calculationHandler mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total] error: Cannot read property 'toLowerCase' of undefined, stack: TypeError: Cannot read property 'toLowerCase' of undefined
sourceanalytix.0	2020-04-15 20:46:03.410	info	(508) Calculation for mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total with value : {"val":7449,"ack":true,"ts":1586976352942,"q":0,"from":"system.adapter.mqtt.0","user":"system.user.admin","lc":1586
sourceanalytix.0	2020-04-15 20:46:03.407	info	(508) First time calc result after initialising
sourceanalytix.0	2020-04-15 20:45:54.245	info	(508) Initialising mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total with configuration {"stateDetails":{"alias":"","consumption":true,"costs":false,"deviceName":"mqtt__0__Wemos12-Wasserzaehler__Wasse
sourceanalytix.0	2020-04-15 20:45:54.245	info	(508) Initialising (2 of 11) state mqtt.0.Wemos12-Wasserzaehler.Wasserzaehler.Total
sourceanalytix.0	2020-04-15 20:45:54.245	error	(508) Sorry unite type kWh not supported (yet), parser.0.Leistung_aufaddiert will be ignored from calculations!
sourceanalytix.0	2020-04-15 20:45:54.244	error	(508) Identifying unit failed, please ensure state has a propper unit assigned or the unit is manually choosen in state settings !`

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
