### ISSUE TITLE
Datenpunkte im Ordner 2020 bleiben bei "0" bei MQTT Datenpunkt

### ISSUE THREAD

**Issue by Easyrunner** [iobroker-community-adapters/ioBroker.sourceanalytix#140]
Unter Version 0.42 bleiben die Werte für Current day/week/month/Year bei einem MQTT Datenpunbkt auf "0"
![2020-04-14 15_54_49-objects - ioBroker](https://user-images.githubusercontent.com/47195199/79261946-d4df0f00-7e90-11ea-89a0-7d9f3121a0fa.jpg)

**Comment by DutchmanNL** [comment]
kommt da ne Meldung im log, kannst du bitte die. raw Daten des objects schicken?

**Comment by kugelkopf123** [comment]
Moin!
Vermutlich habe ich das gleiche Problem...

Fehler im Log: 
`2020-04-15 01:25:46.213 - error: sourceanalytix.0 (19842) [calculationHandler sonoff.0.ESP-SWG2.Gas_Count] error: Cannot read property 'toLowerCase' of undefined, stack: TypeError: Cannot read property 'toLowerCase' of undefined`

Datenpunkt RAW:

```
{
  "from": "system.adapter.sourceanalytix.0",
  "user": "system.user.admin",
  "ts": 1586901600173,
  "common": {
    "name": "ESP-SWG2 Gas  Count",
    "type": "number",
    "role": "value",
    "read": true,
    "write": false,
    "custom": {
      "sourceanalytix.0": {
        "enabled": true,
        "alias": "",
        "state_type": "gas",
        "state_unit": "m3",
        "costs": true,
        "consumption": true,
        "meter_values": true,
        "start_day": 0,
        "start_week": 0,
        "start_month": 0,
        "start_quarter": 0,
        "start_year": 0
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "sonoff.0.ESP-SWG2.Gas_Count",
  "type": "state"
}
```
Vielen Dank für deine Mühe und diesen Adapter! 
Vielleicht sollte noch bedacht werden, was passiert wenn ein Zähler getauscht wird und dieser nun wieder von 0 anfängt zu zählen. Was passiert mit den bereits aufgenommenen Daten? 

Viele Grüße!

**Comment by DutchmanNL** [comment]
Super danke das war der entscheidende Hinweis keine Unit.
Ich nemen den datenpunkt als test case 


Zum Thema reset, seit 0.4.1 erkennt der Adapter wen der Messwert < 1 ist und zählt dan einfach weiter zum Wert hinzu anstatt zurück zu springen

**Comment by kugelkopf123** [comment]
Gibt es schon etwas neues bzgl. dieses Bugs?

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
