### ISSUE TITLE
unit

### ISSUE THREAD

**Issue by tobsi57** [iobroker-community-adapters/ioBroker.sourceanalytix#145]
ist es möglich die Einheit (unit) mm mit aufzunehmen. Ich lass den Regenmesser darüber analysieren und der zählt in mm

**Comment by DutchmanNL** [comment]
wie waehre es damit alle unit bearbeiten und eilig neuen hinzufügen zu koennen :)

<img width="1510" alt="Schermafbeelding 2020-04-19 om 21 46 05" src="https://user-images.githubusercontent.com/7318445/79698145-2ddee680-8287-11ea-9419-27d97c3965ff.png">

**Comment by DutchmanNL** [comment]
fix 0.4.5 concept komplett überarbeitet bitte : https://forum.iobroker.net/topic/31932/major-update-sourceanalytix-0-4-0-complete-code-rebuild/170

lesen
