### ISSUE TITLE
Warnungen im Log

### ISSUE THREAD

**Issue by AlfredSch** [iobroker-community-adapters/ioBroker.sourceanalytix#146]
Hallo,
Seit dem Upgrade habe ich ein paar hundert warnings nach dem Starten des Adapters.
Logeinträge:

sourceanalytix.0 | 2020-04-24 11:01:57.644 | warn | (27672) Object modbus__0__inputRegisters__30073_Import_Tot.2020.consumed.weeks.52 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
-- | -- | -- | --
sourceanalytix.0 | 2020-04-24 11:01:57.638 | warn | (27672) This object will not be created in future versions. Please report this to the developer.
sourceanalytix.0 | 2020-04-24 11:01:57.638 | warn | (27672) Object modbus__0__inputRegisters__30073_Import_Tot.2020.costs.weeks.51 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
sourceanalytix.0 | 2020-04-24 11:01:57.633 | warn | (27672) This object will not be created in future versions. Please report this to the developer.
sourceanalytix.0 | 2020-04-24 11:01:57.633 | warn | (27672) Object modbus__0__inputRegisters__30073_Import_Tot.2020.meterReadings.weeks.51 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
sourceanalytix.0 | 2020-04-24 11:01:57.628 | warn | (27672) This object will not be created in future versions. Please report this to the developer.
sourceanalytix.0 | 2020-04-24 11:01:57.628 | warn | (27672) Object modbus__0__inputRegisters__30073_Import_Tot.2020.consumed.weeks.51 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
sourceanalytix.0 | 2020-04-24 11:01:57.622 | warn | (27672) This object will not be created in future versions. Please report this to the developer.

Gruss
Fred

**Comment by DutchmanNL** [comment]
thank you, already fixed on git will release this weekend https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/ec2dc5cd5b5ed585b9ffa71196cce0c62da34ea6
