### ISSUE TITLE
Startwert soll 0 bleiben

### ISSUE THREAD

**Issue by Nussert** [iobroker-community-adapters/ioBroker.sourceanalytix#147]
Hallo Zusammen,
ist es möglich, dass der Startwert für den Tag immer bei 0 bleiben kann?
Die gelieferten Werte werden automatisch 24 Uhr auf 0 gesetzt.
Wenn ich den Startwert auf 0 setzte ist am nächsten Tag der Vortageswert drin.

Besten Dank vorab.

**Comment by DutchmanNL** [comment]
das ist unnötig den SA rechnet immer mit dem gesammtwert.
Wen dein Zahler sich um 00.00 resettet (was er nicht sollte den fuer SA sollte man einen Gesamtwert nehmen) wird SA immer weiter hoch zählen ab Version 0.4.5.

Sieh dafuer den wert bei current Reading, der zählt immer weiter kumulierend hoch sonst kan man die tages/wochen usw Berechnungen ueberhaupt nicht machen :)
