### ISSUE TITLE
This object will not be created in future versions (20147)

### ISSUE THREAD

**Issue by 7egacy** [iobroker-community-adapters/ioBroker.sourceanalytix#149]
Bekomme für jeden Datenpunkt den der Adapter anlegt im Log folgende Warnung:

sourceanalytix.0 | 2020-04-30 19:13:45.108 | warn | (20147) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
sourceanalytix.0 | 2020-04-30 19:13:45.107 | warn | (20147) Object smartmeter__0__1-0:1_8_2__255__value.2020.costs.weeks.53 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"

Nutze die Version 0.4.2 des Adapters auf einem Raspberry Pi 4 mit Node.js v10.20.1 und dem js controller 3.0.20

**Comment by DutchmanNL** [comment]
Bereits gelöst in 0.4.5 werde demnaest releasen

**Comment by 7egacy** [comment]
Danke für deine tolle Arbeit!

**Comment by DutchmanNL** [comment]
> Danke für deine tolle Arbeit!

Danke für die Blumen 😊
