### ISSUE TITLE
Device Reset erkennen

### ISSUE THREAD

**Issue by Omega236** [iobroker-community-adapters/ioBroker.sourceanalytix#150]
der aktuelle versuch Device-Resets zu erkennen (valueAtDeviceReset) funktioniert leider nicht korrekt (oder ich verstehs nicht). Die akutelle Lösung hat scheinbar 3 Probleme: 
1. nur der erste Reset wird erkannt
2. intransparent da man nur im Raw Modus sieht warum er auf die endgültigen Werte kommt.
3. nur Full-Resets werden erkannt (nicht genauer überprüft).

diese Device-Resets könnten deutlich einfacher behoben werden.

was ist zu tun?
Aktuellen wert mit letztem vergleichen
Wenn aktueller wert < letzter wert (vom überwachentem Datenpunkt, nicht endergebnis), dann die Differenz von den 5 start_xxxx abziehen und diese neuen Werte wieder in den Adapter einlesen.

Wenn du insteresse hast kann ich mir den Code auch mal anschauen.

**Comment by HGlab01** [comment]
oder einfach?
konsumption = Math.max(0, konsumption - konsumption );

**Comment by DutchmanNL** [comment]
> Aktuellen wert mit letztem vergleichen
> Wenn du insteresse hast kann ich mir den Code auch mal anschauen.

hmm ja das klinkt leicht, kannst im adapter code aber vergessen (javascript geht)
Es gibt naehmlich keinen previous state im controller, das existiert nur javascript instanze

desweiteren wuerde diese Berechnung wie du vorschlägst zu Fehlern führen, wen naemlich in der Berechnung ein Aussetzer war oder der wert nur (was passieren kan bei Geräten wie tasmota etc) da er dan anstatt einen basis wert alles kumuliert

Ich halte den reset auf gesamt wert, da die anderen werte nicht zur verfuegung stehen !, am sinnvollsten lasse mich aber gerne belehren mit einem loesung Ansatz der auch bei Adaptern und nicht javascript geht und a

den ein device reset vangt immer bie <1 an irgendwo muss ne haemschwaelle her

**Comment by DutchmanNL** [comment]
so habe mir den code und logic nochmal durchgenommen, folgende loesungs Ansatz 👍 

- wie erwähnt, voriger wert geht nicht diese idee lasse ich dan auch sofort fallen
- direct mit pre/current actions auslösen zerstört die adapter logic
- Das problem wird teils verursacht durch den schwellenwert 1

Also werde ich

- device reset befreien vom schwellenwert
- es wie vorgeschlagen nach der calculation einbauen
- einen 2te Speicherplatz reservieren um es zu detaillieren
- de kumulierten wert transparent auf das tab positionieren

Solltest du einen andere loesungs Ansatz sehen, mit in Achtname der technischen Möglichkeiten wobei bitte beachte adapter Funktionen !== Javascript Funktionen immer gerne

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
