### ISSUE TITLE
Drop down in second instance missing

### ISSUE THREAD

**Issue by Fragggy** [iobroker-community-adapters/ioBroker.sourceanalytix#152]
Hi,

if you install a second instance you are not able to select something from the dropdown in adapter settings:

![image](https://user-images.githubusercontent.com/57753321/81145177-10439980-8f76-11ea-9b7a-26c8e494844a.png)

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
