### ISSUE TITLE
"null" at negative values

### ISSUE THREAD

**Issue by Chris87-ux** [iobroker-community-adapters/ioBroker.sourceanalytix#153]
Once a value change to negative the adapter don't work anymore.

I would like to record the overall perfomance of my heating, so I have one value which is able to change between +15000W to -5000W, but everytime it change below "0" it shows "null".

![image](https://user-images.githubusercontent.com/55442459/81913126-d571df00-95cf-11ea-9a6f-76143a169850.png)

**Comment by DutchmanNL** [comment]
thank you need to check this one out missed it during my research of other items

**Comment by DutchmanNL** [comment]
I tried to reproduce this without luck, can you give me a little more background how and when this occurs ?

![Schermafbeelding 2020-09-04 om 12 23 39](https://user-images.githubusercontent.com/7318445/92229263-79e29e80-eea9-11ea-9069-8fa5bc3fb5ba.png)

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
