### ISSUE TITLE
2 instances in use: Adding one device to instance.0 only, device shows up in both devices

### ISSUE THREAD

**Issue by funky4t** [iobroker-community-adapters/ioBroker.sourceanalytix#155]
Hi guys, I am on version 0.4.2 and using two instances, one (instance.0) for some devices in my home and a second (instance.1) for some power plugs at my parents home, as they are connected via VPN and my iobroker is just doing the job for 4 plugs remote and also we have different power costs/kWh. Though 2 instances is the easiest way to handle that.
Whenever I want to add a new device for instance.0 in the config section of the device, the device shows up in both instances .0 and .1. I tried that several times and it was always the same behavior. I double checked, that instance.1 was not set active when instance.0 was. After hitting "Save" the device-values show up in .0  and .1 and also both instance-sections inside device configuration were set to active although I just clicked instance.0.
But thanks oof far, I love your adapter and cannot wait for coming updates 👍🏼

**Comment by funky4t** [comment]
Additional Information after running both instances for a day. I have devices that were checked with instance.1 and were also automatically selected in instance.0. As mentioned above I could deselect instance.0 manually, so that device should calculate power consumption only in instance.1. But by today all these devices stopped counting at all, no change in consumption still same value in current_day. Looks like deactivating instance.0 is also deactivating instance.1 although .1 on is still shown as active in device setting. So both instances seem to be directly linked, although one shows opposite status than the other.

**Comment by DutchmanNL** [comment]
please retest with JS-Controller 3.x and SA version 0.4.7
