### ISSUE TITLE
Irgendwie rechnet das Ding falsch.

### ISSUE THREAD

**Issue by n3roGit** [iobroker-community-adapters/ioBroker.sourceanalytix#156]
![image](https://user-images.githubusercontent.com/8565847/83323003-0737a680-a25c-11ea-995d-75bdfd3e4c39.png)

Der Zähler ist eigentlich bei ~160KW.

**Comment by guergen1** [comment]
Ja, seit der neuen Version, DutchmanNL arbeitet ja dran, hat aber scheinbar im Moment wenig Zeit dafür. Entweder eine alte Version installieren, oder noch damit leben!

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
