### ISSUE TITLE
Capability to install to versions in parallel?

### ISSUE THREAD

**Issue by HGlab01** [iobroker-community-adapters/ioBroker.sourceanalytix#158]
Good morning,
is there a capability to install the adapter in 2 versions (0.3.0 and 0.4.2)  with 2 instances?
Would make testing of the new version much easier.

Second question:
Is the ToDo: "Migration from < 0.4.0 to new datastructure" still open?

Thanks for your support!

**Comment by DutchmanNL** [comment]
no sorry the ioBroker framework does not allow to install 2 different versions of 1 adapter.
