### ISSUE TITLE
Tageswerte werden nicht angezeigt

### ISSUE THREAD

**Issue by tigertim08** [iobroker-community-adapters/ioBroker.sourceanalytix#159]
Hallo zusammen, 

nach dem Update von 3.0 auf 4.2 werden mir keine Tageswerte mehr angezeigt und auch die Werte bei den Monaten bleiben leer. 

Hat diesen Fehler sonst schon mal wer gehabt?

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
