### ISSUE TITLE
Falscher Zählerstand wenn mehr als zwei Kommastellen

### ISSUE THREAD

**Issue by Wurzelfuchs** [iobroker-community-adapters/ioBroker.sourceanalytix#160]
Leider stimmen die Zählerstände nicht mehr, sobald die Quelle mehr als zwei Nachkomma stellen hat.

**Comment by DutchmanNL** [comment]
please test 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
