### ISSUE TITLE
(3762) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.sourceanalytix#161]
Ist mir heute bei einem Neustart von iOBroker im Log aufgefallen.

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
