### ISSUE TITLE
Nach Raspberry Wechsel Daten weg

### ISSUE THREAD

**Issue by MotschaM** [iobroker-community-adapters/ioBroker.sourceanalytix#162]
Mein Raspberry hab ich versehentlich zerstört, habe die SD Karte in das neue Raspberry, aber jetzt sind leider alle Daten von sourceanalytix weg. Wie und wo kann ich die Daten finden? Wo wurden oder werden diese gespeichert???

**Comment by DutchmanNL** [comment]
die daten befinden sich in der object DB von ioBroker, ich empfehle ein tägliches backup mit backitup :)
