### ISSUE TITLE
Adapter erwartet scheinbar den Typ number für den Datenpunkt-Namen

### ISSUE THREAD

**Issue by drtp** [iobroker-community-adapters/ioBroker.sourceanalytix#166]
Hallo,

bekomme regelmäßig eine Warnmeldung, wenn der nachfolgende Datenpunkt ausgelesen wird.

![2020-07-12 10-50-05](https://user-images.githubusercontent.com/17758445/87242613-ad1b2b00-c42e-11ea-950b-eccdfc60dd77.png)

`
sourceanalytix.0	2020-07-12 10:35:42.034	warn	(691) This object will not be created in future versions. Please report this to the developer.
sourceanalytix.0	2020-07-12 10:35:42.033	warn	(691) Object sourceanalytix.0.hm-rpc__0__NEQ0862336__1__GAS_POWER.2020.consumed.weeks.48 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
--

`

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
