### ISSUE TITLE
Adapter in Version 0.4.2 scheint Namenssuche der Datenpunkte zu blockieren

### ISSUE THREAD

**Issue by drtp** [iobroker-community-adapters/ioBroker.sourceanalytix#167]
Wenn der Adapter bei mir Datenpunkte angelegt hat, funktioniert die Namenssuche nicht mehr. Es wird ewig die Sanduhr angezeigt.

![2020-07-12 08-37-04](https://user-images.githubusercontent.com/17758445/87242693-46e2d800-c42f-11ea-992d-6a26afc14c77.png)

Das Problem lässt sich mit Deinstallieren und Installieren des Adapters und Anlegen der Datenpunkte reproduzieren.

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
