### ISSUE TITLE
Datenpunkte NULL nach Tageswechsel

### ISSUE THREAD

**Issue by martin2704-Ger** [iobroker-community-adapters/ioBroker.sourceanalytix#169]
**Describe the bug**  
Um Mitternacht werden alle Datenpunkte im Knoten 2020 auf den Wert NULL gesetzt

**To Reproduce**  
Tageswechsel um Mitternacht

**Expected behavior**  
Werte in Datenpunkte bleiben erhalten nach Datumswechsel

**Versions:**  
 - Adapter version: 0.4.5
 - JS-Controller version: 3.1.4
 - Node version: 10.21.0
 - Operating system: Linux/Raspbian

**Comment by DutchmanNL** [comment]
fixed 0.4.7-alpha.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a47eb48394e58548ae58a9e9d75cea6401d039d1
