### ISSUE TITLE
Auswahl Elektro / Gas / …

### ISSUE THREAD

**Issue by FriMatze** [iobroker-community-adapters/ioBroker.sourceanalytix#17]
Moin, wenn ich Gas auswähle, dann speichere und dann wieder in die Einstellungen gehe wird wieder Elektric angezeigt.

Version 0.1.6

![4b94d199-aa6c-449e-bf06-bb99107c5991](https://user-images.githubusercontent.com/31760616/51270842-3e3e4c80-19c6-11e9-9d88-355b678eb13f.jpeg)

**Comment by DutchmanNL** [comment]
stimmt, version 1.8 ist eine dev version in 0.2.0 wird dies gefixt.

**Comment by DutchmanNL** [comment]
fixed in 0.1.9
