### ISSUE TITLE
0-Werte und korrekte weiter Berechnung

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.sourceanalytix#197]
Bei Problemen mit NULL Werten, durch fehlerhaft gelieferte Datenbasis (z.B durch Discovergy Server Ausfall) oder durch eigenen ioB Server Ausfall könnte man versuchen den letzten gelesenen Datenpunkt immer irgendwo zwischen zu Puffern. Wird dann nach einem NULL wert wieder ein "normler" Wert gelesen, wird als Berechnungsgrundlage der letzte im Puffer befindliche Wert > 0  als Berechnungsbasis heran gezogen.

Damit könnte man solche 0-Ausfälle mit anschließend falscher Berechnung vermeiden.

![2020-09-16 20_21_19-Flot Chart](https://user-images.githubusercontent.com/44617472/93379893-cab9a600-f85e-11ea-9898-16c0528596ba.png)

**Comment by DutchmanNL** [comment]
danke, ich werde mir mal Gedanken dazu mache wie ma am besten Puffern kan. Allgemein würde ich es im Arbeitsspeicher machen aber Beispiel ioBroker Ausfall wird damit nicht gedeckt

**Comment by DutchmanNL** [comment]
ab version 0.4.8-alpha.7 werden null werte fuer Berechnungen ignoriert

**Comment by DutchmanNL** [comment]
Solved in 0.4.8-Beta.0 which will be released this weekend, alpha 0.4.8-Alpha.13 is already available for install and has all fixes included.
Please do not install any version of 0.4.8 lower than alpha 13 ! (Or wait for beta release on Sunday 15-01-2021)
