### ISSUE TITLE
source überschreibt Datenpunkte des zu überwachenden Gerätes

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.sourceanalytix#201]
Nach dem Update auf die 0.4.7 werden Gerätedaten überschrieben:
![grafik](https://user-images.githubusercontent.com/34395245/93663185-243ff180-fa66-11ea-8a1b-990df37b5faf.png)
Gleichzeitig gibt es den Fehler: 
![grafik](https://user-images.githubusercontent.com/34395245/93663200-3ae64880-fa66-11ea-9b7e-ee0045be193a.png)
Der scheint allerdings in einem anderen Issue behandelt zu werden!

**Comment by DutchmanNL** [comment]
Dublicated by https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/issues/191

Bitte bei dem datenpunkt den default Wert entfernen, ist leider ein bug im JS-Controller wird in naester Version vom js-Controller behoben

**Comment by guergen1** [comment]
Wie oder wo entferne ich den Default DP?

**Comment by DutchmanNL** [comment]
im raw object steht ein def: "",

diese Zeile bitte komplett entfernen, beispiel : 

```
  "_id": "0_userdata.0.Neues_Objekt",
  "type": "state",
  "common": {
    "name": "Neues Objekt",
    "role": "",
    "type": "number",
    "read": true,
    "write": true,
    "desc": "Manuell erzeugt",
    "min": 0,
    "max": 100,
    "def": 0,
    "unit": "%"
  },
```

wird

```
  "_id": "0_userdata.0.Neues_Objekt",
  "type": "state",
  "common": {
    "name": "Neues Objekt",
    "role": "",
    "type": "number",
    "read": true,
    "write": true,
    "desc": "Manuell erzeugt",
    "min": 0,
    "max": 100,
    "unit": "%"
  },
```
Oder hier auf den Papierkorb bei Standardwert 
![Schermafbeelding 2020-09-19 om 11 39 02](https://user-images.githubusercontent.com/7318445/93664103-b945e900-fa6c-11ea-99aa-b61f622e3957.png)

**Comment by guergen1** [comment]
Grade gefunden!
Danke!
