### ISSUE TITLE
Please replace the default logo

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.sourceanalytix#21]

**Comment by DutchmanNL** [comment]
Will be fixed before 0.5 release and before Stanley repro, waiting for a good design.

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/0c2f00bbb2f965225008c1a85029b31b83f785cc
