### ISSUE TITLE
homematic calculation error

### ISSUE THREAD

**Issue by SlrG** [iobroker-community-adapters/ioBroker.sourceanalytix#210]
1. Verify if there is not already an issue requesting the same
I tried to search with various keywords, but found no other issue describing my problem.
 
2. Is this really a bug of current code, or an enhancement request ?
For me it really seems to be a bug. (Though I also had (the same?) problems with the adapters predecessor script, too.)

**To Reproduce**  
1. Install SourceAnalytics
2. Enable SourceAnalytics for HM-ES-PMSw1-Pl on ENERGY_COUNTER of channel 2.
![iobroker01](https://user-images.githubusercontent.com/978967/95011158-014d3a00-062f-11eb-9f33-d62400ae9221.png)
The starting values were all zero, the current values were set by SourceAnalytics itself and not changed manually.
3. Enable meter readings only and wait till the end of month.
4. Enable consumed values
5. Wait at least a day

**Describe the bug**  
![sourceanalytics01](https://user-images.githubusercontent.com/978967/95010754-31dfa480-062c-11eb-93c0-c071f9fe5706.png)

As seen in the above screenshot, the consumed value for the day is 101.644 kWh, which is not correct, but the overall value of ENERGY_COUNTER counting everything up to the current point in time. See here: 

![raspberrymatic02](https://user-images.githubusercontent.com/978967/95011393-af0d1880-0630-11eb-984a-40be850039f2.png)

Now this much to high "daily value" gets added again and again and does not reset to zero each day, like it should. Today on the 4th day of October I'm at 405.944 kwh, which is ridiculously high.

Either this breaks the meter readings, too or something broken in the meter readings causes the above results. See here:
![sourceanalytics02](https://user-images.githubusercontent.com/978967/95011556-d6b0b080-0631-11eb-8cca-b11697a56813.png)
The value of 93.837 of September is correct, as I enabled SourceAnalytics in the middle of September. The October reading is not correct, as I enabled the consumed values too, but something goes wrong as seen in the second screenshot above.

**Expected behavior**  
Count only what is consumed each day, month and year. At the end of each month store the ENERGY_COUNTER value in meter readings. Account for overflows and counter resets in both cases.

**Versions:**  
 - Adapter version: 0.4.7
 - JS-Controller version: 3.1.6
 - Node version: 12.18.3
 - Operating system: buanet/iobroker docker

**Comment by DutchmanNL** [comment]
can you show me please the states of the HomeMatic device and which one your are logging

**Comment by SlrG** [comment]
Thank you for the quick response. Here it is:

![iobroker02](https://user-images.githubusercontent.com/978967/95013546-36fb1e80-0641-11eb-864d-712266defdae.png)

I'm logging the ENERGY_COUNTER, which counts upwards continuously until it has an overflow or is reset. AFAIK there is no other value I could log to get the results I want?

**Comment by DutchmanNL** [comment]
Hmm, i think the def0 valu is Cassini this issue will look into it thanks all Info i meedeed

**Comment by DutchmanNL** [comment]
Solved in 0.4.8-Beta.0 which will be released this weekend, alpha 0.4.8-Alpha.13 is already available for install and has all fixes included.
Please do not install any version of 0.4.8 lower than alpha 13 ! (Or wait for beta release on Sunday 15-01-2021)
