### ISSUE TITLE
Negative Werte wenn Gerät den verbrauch vergisst.

### ISSUE THREAD

**Issue by n3roGit** [iobroker-community-adapters/ioBroker.sourceanalytix#215]
Leider vergessen meine Tasmota Geräte ab und an mal ihren total verbrauch. Dann hab ich plötzlich überall negativen Stromverbrauch was von dem Plugin ja auch korrekt berechnet wird.

Vielleicht wäre es möglich eine Option zu bauen, die beim Verlust (verbrauch ist wieder bei 0) dann trotzdem weiter rechnet.

if aktueller verbrauch < als das war der adapter bereits ausgelesen hat
dann
addiere den neuen verbrauch einfach dazu.

**Comment by DutchmanNL** [comment]
ist bereits implementiert in version 0.4.x (morgen kommt 0.4.8 beta in latest)
