### ISSUE TITLE
Deprecated Dependencies

### ISSUE THREAD

**Issue by DomKue** [iobroker-community-adapters/ioBroker.sourceanalytix#222]
Hi,

bei der Installation via npm ergeben sich zwei Warnings zu deprecated Paketen:
- request@2.88.2 (wird eingestellt, wie im Februar mitgeteilt wurde)
- har-validator@5.1.5
Diese Abhängigkeiten sollten nach Möglichkeit aufgehoben/ausgetauscht werden, um langfristig weiterhin zu funktionieren.

**Comment by DutchmanNL** [comment]
Danke, request werde ich rausnehmen braucht der Adapter nicht.

har-validator kommt nicht aus meinen dependencys könnte vom Controller oder ne unterliegenden Abhängigkeit kommen daarna kan ich leider nix machen

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/package.json#L30

**Comment by DomKue** [comment]
Stimmt - der har-validator ist u.a. eine dependency vom request, insofern direkt mit erledigt :)

**Comment by DutchmanNL** [comment]
Solved in 0.4.8-Beta.0 which will be released this weekend, alpha 0.4.8-Alpha.13 is already available for install and has all fixes included.
Please do not install any version of 0.4.8 lower than alpha 13 ! (Or wait for beta release on Sunday 15-01-2021)
