### ISSUE TITLE
Keine Werte für "PreviousDay" / 0.4.8-alpha.2

### ISSUE THREAD

**Issue by funky4t** [iobroker-community-adapters/ioBroker.sourceanalytix#242]
Hi Leute,
bin noch recht neu unterwegs mit eurem Adapter, habe aber weder hier noch im Forum mein "Problem" wiedergefunden. Ich hab bei einer Steckdose die Messung aktiviert, hat nen bissl gedauert, bis ich verstanden habe, was die "Startwerte" bedeutet und dass man sie auch leer lassen kann, wenn man z.B. den Totalenergy misst. Die grundlegende Konfiguration der Dose ist hier:

<img width="1236" alt="Bildschirmfoto 2020-11-08 um 09 51 50" src="https://user-images.githubusercontent.com/57875762/98460985-25a9b280-21a9-11eb-8763-c4b4bdb84018.png">

Okay, soweit so gut. Die Ermittlung des Verbrauchs funktioniert soweit gut. Und die einzelnen Tage wertet der Adapter auch ordentlich aus, siehe Screenshot Nr. 2. Klar dass beim Start am Freitag dieser übermässig hoch ist, aber ich wollte den nicht auf Null zurücksetzen, weil andere Adapter drauf zugreifen.

<img width="1244" alt="Bildschirmfoto 2020-11-08 um 09 51 07" src="https://user-images.githubusercontent.com/57875762/98461067-86d18600-21a9-11eb-8233-1619ed863a35.png">

Bis heute hat der Adapter die drei Tageswerte korrekt erfasst und korrekt in die Wochenübersicht geschrieben. Allerdings bleibt der Wert bei "PreviousDay" leer, dieser müsste doch mit Vergleich "Heute-1" aus den Tageswerten zu ermitteln sein. 

Habe ich was falsch konfiguriert oder vergessen? Bin auf der 0.4.8-alpha.2

Danke für eure Hilfe!

**Comment by DutchmanNL** [comment]
chips das wollte ich dieses WE lösen danke fuer den reminder :/

**Comment by DutchmanNL** [comment]
Solved in 0.4.8-Beta.0 which will be released this weekend, alpha 0.4.8-Alpha.13 is already available for install and has all fixes included.
Please do not install any version of 0.4.8 lower than alpha 13 ! (Or wait for beta release on Sunday 15-01-2021)
