### ISSUE TITLE
Stromverbrauch Einzelgeräte VS Stromzähler

### ISSUE THREAD

**Issue by n3roGit** [iobroker-community-adapters/ioBroker.sourceanalytix#246]
Moin moin,

dein Adapter funktioniert mittlerweile wirklich gut! Großes Lob von mir =)

Ich habe aber mal eine Frage und vielleicht hast du ja eine Lösung dafür.

Ich habe bereits seit einer Weile folgendes gebaut:
Ich nehme alle Verbrauchsdaten der Einzelgeräte, die ich überwache und rechne diese gegen den verbrauch des Stromzählers. Dadurch weiß ich, ob ich die größten Stromverbraucher bereits überwache oder nicht.

![image](https://user-images.githubusercontent.com/8565847/98914108-8e09d400-24c8-11eb-8ae9-c4ff83cf5d71.png)

Alle Werte von (sourceanalytix.0.sonoff*ENERGY_Total.Current_Reading) addieren und in GlobalKW schreiben.
Differenz von Stromzähler und GlobalKW in GlobalKWDiff schreiben.

![image](https://user-images.githubusercontent.com/8565847/98913148-459de680-24c7-11eb-931f-4021fed50140.png)

Hier die Blocky dazu:
https://pastebin.com/raw/dncpck9t
https://pastebin.com/raw/rRxEV1s3

Dummerweise springt der Wert der aus GlobalKW und Stromzähler berechnet wird gerne mal ab 00:01 auf einen niedrigeren Wert. Das konnte ich mir bis dahin nicht erklären.

Fehler in Berechnung von GlobalKWDiff. Neu: 6344.162 Alt: 8466.877

Dadurch glaubt der Adapter das sehr hohe Kosten entstanden sind..

Hast du irgendeine Idee wie man das schöner umsetzen könnte? Oder möchtest du möglicherweise sowas in dem Adapter implementieren?

**Comment by DutchmanNL** [comment]
Das bekannte DEF: 0 problem, nimm das mal raus aus deinen Datenpunkten :)

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/issues/191

**Comment by n3roGit** [comment]
Dank dir das werde ich gleich mal testen!

**Comment by DutchmanNL** [comment]
und sollte es das nicht sein machen wir das issue wieder auf und schauen was los ist ;)
