### ISSUE TITLE
Set currency unit in configuration

### ISSUE THREAD

**Issue by Aare07** [iobroker-community-adapters/ioBroker.sourceanalytix#247]
I would appreciate it if the currency unit could be set in the main configuration of the adapter.
Although only a minor optical problem within the created costs datapoints, it would be great if, in addition to € the unit could be set to different units (CHF, złoty, $,...).

Or in other words:
Resulting costs Datapoints now created static with €: `  "unit": "€", `
Should be configurable in adapter to create the costs datapoints in other currencies units:

Thank you for the great work from a user outside the EU :)

**Comment by DutchmanNL** [comment]
good one, enhancement accepted I thought already did by using the unit from ioBroker settings but just realizing I did it in my head but not in the code

**Comment by DutchmanNL** [comment]
Solved in 0.4.8-Beta.0 which will be released this weekend, alpha 0.4.8-Alpha.13 is already available for install and has all fixes included.
Please do not install any version of 0.4.8 lower than alpha 13 ! (Or wait for beta release on Sunday 15-01-2021)
