### ISSUE TITLE
currentWeek doesn't restart on Monday?

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.sourceanalytix#257]
I installed this module yesterday (Sunday) and today (Monday) see this:

![image](https://user-images.githubusercontent.com/3794098/100639703-d08b3780-3335-11eb-80ec-dd20a6fb1a8a.png)

As you can see, there is already a reading on Sunday this week, which is actually yesterday's (which is in last week) reading.

I notice `currentYear.consumed.02_currentWeek` shows 4.893kWh as expected but there is no reading for `currentYear.consumed.02_previousWeek`. Shouldn't that be 3.705kWh in this scenario?

FYI, objects under `currentYear.consumed.previousWeek` (not shown in the screenshot) were all zero.

**Comment by DutchmanNL** [comment]
solved starting from 0.4.8-alpha.5
