### ISSUE TITLE
Log wird mit Resetmeldungen geflutet

### ISSUE THREAD

**Issue by stumpyofpain** [iobroker-community-adapters/ioBroker.sourceanalytix#273]
Guten Tag

Ich hab letzte Woche angefangen ioBroker zu nutzen und habe dabei direkt Source Analytix mit installiert und eingerichtet.
Nun ist mir letztens aufgefallen, das ich ständig Warnungen im Log angezeigt bekomme, das ein Reset festgestellt wurde.
Ist das schlimm?
Was kann ich dagegen tun?
Anbei die Fehlermeldung.

```
sourceanalytix.0 | 2020-12-18 22:27:34.877 | warn | (1077) Device reset detected for  alias.0.Florian_Schlafzimmer.Fernseher_Flo_Stromverbrauch_Heute.ACTUAL  store current value 535.2069999999999 to value of reset
-- | -- | -- | --
sourceanalytix.0 | 2020-12-18 22:26:15.983 | warn | (1077) Device reset detected for  alias.0.Florian_Schlafzimmer.NAS_Flo_Stromverbrauch_Heute.ACTUAL store  current value 980.8049999999998 to value of reset

sourceanalytix.0 | 2020-12-18 22:25:54.837 | warn | (1077) Device reset detected for  alias.0.Florian_Schlafzimmer.Fernseher_Flo_Stromverbrauch_Heute.ACTUAL  store current value 534.6279999999999 to value of reset
sourceanalytix.0 | 2020-12-18 22:24:45.964 | warn | (1077) Device reset detected for  alias.0.Florian_Schlafzimmer.NAS_Flo_Stromverbrauch_Heute.ACTUAL store  current value 980.1239999999998 to value of reset
sourceanalytix.0 | 2020-12-18 22:24:14.876 | warn | (1077) Device reset detected for  alias.0.Florian_Schlafzimmer.Fernseher_Flo_Stromverbrauch_Heute.ACTUAL  store current value 534.05 to value of reset
```

**Expected behavior**  
Keine Warnungen / Fehlermeldungen im Log.

**Versions:**  
 - Adapter version: 0.4.8-alpha.2 (2020-10-08)
 - JS-Controller version: 3.1.6
 - Node version: v10.23.0
 - Operating system: ubuntu 20.04

**Comment by DutchmanNL** [comment]
fixed ab 0.4.8-alpha.7 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/b876d641fbdddc9068239721d69c1515190aaafc
