### ISSUE TITLE
Support fur Wärmepumpe

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.sourceanalytix#28]
- Du hast die Möglichkeit geschaffen einen Normalstrom-Tarif, einen Nach-Stromtarif und einen Wert für die Produktion anzugeben. Ich hätte noch einen weiteren Vorschlag den hier sicher einige (inklusive mir :)) nutzen: Einen speziellen Tarif für eine Wärmepumpe.[/quote]habe 

https://forum.iobroker.net/viewtopic.php?f=36&t=20897&start=220#p222665

Dutchman :
kein problem, braucht man dafür einen oder 2 werte ich habe etwas gehört von HT und NT (tag und nach bzw hochtrieb und niedertarief) ?
wen ich die Antwort hab baue ich es ein :

**Comment by DutchmanNL** [comment]
done in 0.2.1 ! :)

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/43244ffaf4506b03a5cd7b8b23a04a4d22493daa

**Comment by darkiop** [comment]
Super :) Vielen Dank !!

**Comment by DutchmanNL** [comment]
so, definitief gelost in 0.2.24 ;)

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/aa06757b2eb7ddfa05cbebffbab1ad2203dad450
