### ISSUE TITLE
Zusätzliche Wochen / Monats / Quartalsdatenpunkte für das aktuelle Jahr

### ISSUE THREAD

**Issue by stumpyofpain** [iobroker-community-adapters/ioBroker.sourceanalytix#280]
Guten Tag

Ich wollte mit InfluxDB und Grafana meinen monatlichen Stromverbrauch in einem Balkendiagram darstellen, leider funktioniert das nicht so wie ich möchte.

Aufgrund dessen habe ich dann SourceAnalytix installiert und meine Messquellen hinzugefügt.
Jetzt wollte ich so langsam damit anfangen, das Visualisierung damit aufzubauen, jedoch ist mir aufgefallen, dass das "current Year" keine Monate / Wochen / Tage mehr aufzeichnet sondern nur noch die aktuellen und die vorherigen.
Somit kann ich das leider derzeit noch nicht visualisieren, da die Datenpunkte für 2021 ja noch nicht vorhanden sind.

Da ich auch die Jahresübersicht immer aktuell haben möchte, müsste ich mit der derzeitigen Einstellung das aktuelle Jahr ja immer anfang des Jahres neu in Influxdb anpassen.

Daher wäre es schön, wenn du diese im CurrentYear ergänzen könntest und diese zum Anfang des neuen Jahres automatisch auf 0 gesetzt werden.

**Comment by DutchmanNL** [comment]
beim initialisieren bzw erstellen der Struktur fuer ein Jahr werden alle datenbunte auf 0 eingestellt, entweder ich vestehe dich falsch oder wir reden ahnender vorbei :)

**Comment by DutchmanNL** [comment]
glaube du meintest das hier, doch falsch verstanden :)

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/e768734bebd6ebc47b293e18193cecb4515fe871
