### ISSUE TITLE
Warnings with js-controller 3.2.6

### ISSUE THREAD

**Issue by coyote1** [iobroker-community-adapters/ioBroker.sourceanalytix#296]
With js-controller 3.2.6 there are warnings like this:

sourceanalytix.0    2021-01-12 19:18:55.947    warn    (17368) State "sourceanalytix.0.javascript0StromEGkWh.2021.consumed.quarters.1" has no existing object, this might lead to an error in future versions

sourceanalytix.0    2021-01-12 19:18:55.927    warn    (17368) State "sourceanalytix.0.javascript0StromEGkWh.currentYear.consumed.2021.05_currentYear" has no existing object, this might lead to an error in future versions

**Comment by DutchmanNL** [comment]
solied by : [Bugfix : {quarters.1" has no existing object}](https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/6d4b06f00a5857db9bb87f31675b36fc22279c2b) [Bugfix : 05_currentYear" has no existing object, this might lead to a…](https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/a2dc763e2115c4d3d09d95821832997d22393652)

released by [v0.4.8-alpha.15](https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/bff75e4d3330b9d3313b1b9cd7c1cb0ac4855e84)
