### ISSUE TITLE
in the objects I see results of February 2021 ?

### ISSUE THREAD

**Issue by radebold** [iobroker-community-adapters/ioBroker.sourceanalytix#299]
Hi

i run the actually adapter 0.4.8 alpha 12

in the objects I see results of February 2021 ?

![image](https://user-images.githubusercontent.com/25064101/104717444-9b8e4500-5729-11eb-8951-2a1479c2c3d8.png)

**Comment by DutchmanNL** [comment]
week is not February months are on months not in weeks :)
