### ISSUE TITLE
Adapter calculation incorrect.

### ISSUE THREAD

**Issue by FlexerJR** [iobroker-community-adapters/ioBroker.sourceanalytix#30]
Hey Dutchman ;)

I'm using Homematic IP Devices. When entering the current meter reading i discovered that HMIP will show the value in Wh not in kWh. I inserted the Wh Value.

When i look in the Datatree of Sourceanalytix I can see Meter Reading converted from Wh in kWh. Thats correct. But if I take a closer look to cost and consumption I can observe that these Data is calculated with the reading of Wh not kWh.

Best regards
:)

**Comment by DutchmanNL** [comment]
start values must be provided in kWh, questions is if its clear / interface change needed or documentation ?

**Comment by FlexerJR** [comment]
The setting page should point out that all entries must be made in kWh. Maybe later adapter could provide transform meter readings from Wh in kWh automatically

**Comment by DutchmanNL** [comment]
> Maybe later adapter could provide transform meter readings from Wh in kWh automatically

the problem is, I don't want to make the input fields to complex.
So ensuring the values are entered in kilo looks for me the best result as otherwise an additional setting must be made.

We will handle that part before stable release to have a clear user-friendly interface
