### ISSUE TITLE
kein Objektbaum zu sehen - Adapter ist grün

### ISSUE THREAD

**Issue by Day1983** [iobroker-community-adapters/ioBroker.sourceanalytix#300]
Hallo,

ich habe den Adapter über URL install.
Die Instanz ist da und grün - aber unter Objekte-Baum ist die Inztanz nicht da...

Was kann ich tun?

Vielen Dank.

**Comment by DutchmanNL** [comment]
Hast du states aktiviert um welcher Nirvana ausgewertet werden sollen ?

**Comment by Day1983** [comment]
Sorry, hatte die funktionsweise nicht verstanden...

Jetzt schon, nach dem aktivieren der states war auch der Baum da... Sorry

**Comment by DutchmanNL** [comment]
> Sorry, hatte die funktionsweise nicht verstanden...
> 
> Jetzt schon, nach dem aktivieren der states war auch der Baum da... Sorry

tips fuer die Docu ? :P
