### ISSUE TITLE
sourceanalytix wird in Iobroker nicht gelistet

### ISSUE THREAD

**Issue by FraatGIT** [iobroker-community-adapters/ioBroker.sourceanalytix#312]
Hallo, 
in der Übersicht der Adapter die in Iobroker installiert werden können wird sourceanalytix nicht gelistet. Wie kann ich den Adapter installieren?

**Comment by DutchmanNL** [comment]
Der Adapter ist momentan nur als Beta verfügbar und wird innerhalb der mästen 2 Monate auch im stable (Produktion) installierbar sein

momentan also nur als beta
