### ISSUE TITLE
Frage - Erkennung von - und + Leistung möglich? 

### ISSUE THREAD

**Issue by Schmello** [iobroker-community-adapters/ioBroker.sourceanalytix#321]
Hallo,

Ich lese über Tasmoat meinen Zähle raus.
Dieser zeigt mir bei Einspeisung ins Netz über die PV Anlage den Wert in z.b. -200 W.
Der bezug aus dem Netz wird normal ohne ein vorzeichen angezeigt.
Leider kann ich das gerade nicht ausprobieren, da die PV Anlage zu klein ist um gerade zu viel Strom zu Produzieren das eine Einspeisung möglich ist. Auch ob nach dem - ein Leerzeichen kommt also entweder (-200 W) oder (- 200 W) bin ich mir gerade nicht ganz sicher.
Gibt es die möglichkeit das mir die Kwh für + und - bereich separat angezeigt/in Kwh errechnet werden?

**Comment by DutchmanNL** [comment]
SA macht fuer dich die Berechnungen, dein vorhaben braucht ein script was die - bzw + werte in einen separaten Datenpunkt schreibt und da kannst du es mit Sa auswerten
