### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by obodeldog** [iobroker-community-adapters/ioBroker.sourceanalytix#35]
Hi. Nice idea.
When I tried it with one "Wh" value I get the following log:
`

sourceanalytix.0 | 2019-01-26 06:42:01.715 | warn | Adapter SourceAnalytix stopped !
-- | -- | -- | --
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:150:9)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | at initialize (/opt/iobroker/node_modules/iobroker.sourceanalytix/main.js:171:29)
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | TypeError: Cannot read property 'toLowerCase' of undefined
sourceanalytix.0 | 2019-01-26 06:42:01.715 | error | uncaught exception: Cannot read property 'toLowerCase' of undefined
sourceanalytix.0 | 2019-01-26 06:42:01.713 | info | Activate SourceAnalytix for : knx.0.Sonstiges.Energie.Energiezähler_Waermepumpe_-_Wirkenergie_A__(Wh)
sourceanalytix.0 | 2019-01-26 06:42:01.687 | info | starting. Version 0.2.26 in /opt/iobroker/node_modules/iobroker.sourceanalytix, node: v8.15.0

`

**Comment by obodeldog** [comment]
Hi! Yes, no unit :-)

**Comment by DutchmanNL** [comment]
Clear thanks, will provide a fix by end of day

**Comment by obodeldog** [comment]
Perfect, thanks

**Comment by DutchmanNL** [comment]
fixed, please test latest version from GitHub (not on NPM yet!)

**Comment by DutchmanNL** [comment]
fixed in 0.2.27
