### ISSUE TITLE
Adapter Rot seit update auf 0.2.27

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.sourceanalytix#39]
`Adapter Rot seit update auf 0.2.27

host.Medion | 2019-02-10 20:27:55.095 | error | startInstance system.adapter.sourceanalytix.0: required adapter "null" not found!
-- | -- | -- | --

`

**Comment by sigi2345** [comment]
Bin wieder zurück gegangen. ( 0.2.26 ) Geht so wieder.

**Comment by DutchmanNL** [comment]
fixed please test

**Comment by DutchmanNL** [comment]
fixed in 0.2.27

**Comment by sigi2345** [comment]
Funktioniert, Adapter Grün.
