### ISSUE TITLE
Values input via Vis are not recognized as changed

### ISSUE THREAD

**Issue by Kaskadeur111** [iobroker-community-adapters/ioBroker.sourceanalytix#47]
I have a manual input variable "Stromzaehler" which is enabled in Sourceanalytics (Cost and Consumption). Where i want to put in my Current Readings once per day.

If i change the Value via admin GUI directly, the change gets recognized and Values in sourceanalytix.0 Objects are calculated and refreshed correctly.

But i want to input the value via Mobile Phone in a Vis view.

If i change the Value via vis "ctrl input + set button" Control or "ctrl input" Control, i can see the Variable "Stromzaehler" in admin gets changed, but sourceanalytix doesnt calculate or refresh the Values in sourceanalytix.0 objects.

Using SourceAnalytix 2.24 currently.

**Comment by DutchmanNL** [comment]
very hard to see where it goes wrong and reproduce on my machine, would it be possible to have a look at you setup together with a team viewer session ?

**Comment by DutchmanNL** [comment]
cannot reproduce and no feedback, will close for know. If any news please let me know
