### ISSUE TITLE
Fehler beim Anlegen der Instanz

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.sourceanalytix#48]
Leider kann ich den Adapter in der aktuellen Beta-Version garnicht in Betrieb nehmen.
Wenn ich Ihn vom Git installiere funktioniert alles, sobald ich dann versuche eine Instanz anzulegen bekomme ich folgenden Fehler im Log:

`iobroker	2019-03-04 23:31:12.328	error	at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
iobroker	2019-03-04 23:31:12.328	error	at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
iobroker	2019-03-04 23:31:12.328	error	at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
iobroker	2019-03-04 23:31:12.328	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:133:20)
iobroker	2019-03-04 23:31:12.328	error	at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
iobroker	2019-03-04 23:31:12.328	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
iobroker	2019-03-04 23:31:12.328	error	at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
iobroker	2019-03-04 23:31:12.328	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:529:34)
iobroker	2019-03-04 23:31:12.328	error	at Install.createInstance (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:683:34)
iobroker	2019-03-04 23:31:12.328	error	at Object.getAdapterDir (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:799:17)
iobroker	2019-03-04 23:31:12.328	error	TypeError: Cannot read property 'substring' of undefined
iobroker	2019-03-04 23:31:12.328	error	^
iobroker	2019-03-04 23:31:12.328	error	/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:799 if (adapter.substring(0, appName.length + 1) === appName + '.')`

**Comment by DutchmanNL** [comment]
was passiert wen du ihn über den admin installierst ?

**Comment by DutchmanNL** [comment]
@peoples0815 bitte neue version von GitHub laden, was passiert jetzt ?
