### ISSUE TITLE
Elektroauto 

### ISSUE THREAD

**Issue by FriMatze** [iobroker-community-adapters/ioBroker.sourceanalytix#62]
Moin, unter Berechnungen den Punkt „Elektro Auto“ hinzufügen. 

Gruß

**Comment by DutchmanNL** [comment]
hat dieser einen anderen Tarif ?

**Comment by FriMatze** [comment]
Bei mir nicht. Aber es besteht die Möglichkeit das der Anschluss zum Laden einen eigenen Zähler hat.

**Comment by darkiop** [comment]
Guten Morgen, passend dazu... ich richte gerade den Mercedes.me Adapter ein und berechne mir damit die gefahrenen KM pro Tag. Wäre das nicht auch etwas für SourceAnalytix? Grüße Thorsten

**Comment by DutchmanNL** [comment]
> Guten Morgen, passend dazu... ich richte gerade den Mercedes.me Adapter ein und berechne mir damit die gefahrenen KM pro Tag. Wäre das nicht auch etwas für SourceAnalytix? Grüße Thorsten

theoretisch ja man koennte die kosten pro Kilometer ermitteln !
Ich bastle mal was dazu, was währe ein eigemeiner basis preis per. km ?

**Comment by darkiop** [comment]
Preis? Gute Frage - ich würde mal den Durchschnittspreis für E5, E10 und Diesel vorschlagen.

Hier die RAW vom DP:

{
  "from": "system.adapter.mercedesme.0",
  "user": "system.user.admin",
  "ts": 1567111265048,
  "common": {
    "name": "distanceReset",
    "type": "mixed",
    "role": "indicator",
    "write": false,
    "read": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "mercedesme.0.[FIN].status.distanceReset",
  "type": "state"
}

Der beinhaltet die Gesamt-km.

**Comment by DutchmanNL** [comment]
> Der beinhaltet die Gesamt-km.

könntest du dem im common bitte noch die mit km mitgeben ?

```
  "common": {
    "unit":"km"
  },
```

dan kann ich das automatisch auslesen lassen (werde es auch configurable machen).
preis ist halt einstellbar, muss mal schauen wie ich das im config screen übersichtlich hinbekomme wird ganz schone. voll da

**Comment by darkiop** [comment]
Ich werd das mal bei tombox beim mercedes.me Adapter platzieren

**Comment by TA2k** [comment]
Ist gefixt aber eigentlich gibt es den Punkt history. In dem mit der tankerkönig api die exakten kosten pro kilometer aufgezeichnet werden.

**Comment by darkiop** [comment]
Super vielen Dank :)

Meine Idee für SourceAnalytix war das hier damit abzulösen:

![grafik](https://user-images.githubusercontent.com/205119/71024978-679bb700-2106-11ea-8dff-42b92f2efa0b.png)

Aktuell schreibe ich so einmal kurz vor 0 Uhr die gefahrenen KM weg und berechne die Tages-KM.

**Comment by DutchmanNL** [comment]
jup die basis Funktionen machen das ja barets halt. nur nicht fuer km bau ich ein

**Comment by DutchmanNL** [comment]
man kan jetzt selber kost units definieren ab 0.4.7
