### ISSUE TITLE
Watt Berechnung ohne Funktion 0.2.29

### ISSUE THREAD

**Issue by Xoroles** [iobroker-community-adapters/ioBroker.sourceanalytix#68]
Hallo Zusammen,

in der neuen Version 0.2.29 wurde ja die Berechnung mit Hilfe von Watt Werten ermöglicht. 

Leider ist dies noch ohne korrekte Funktion. 
Anbei die Zeile um die es geht
https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/56ddc892493e0e064b5fcc11e50dac7a48e05d35/main.js#L762
Dort wird das Cache Array 
w_values.calc_reading 
bei jeder anderen Id neu Instanziert, dadurch wird w_values.calc_reading nie wirklich aufgebaut, da immer nur der letzte Wert enthalten ist. Und danach von einem anderen State wieder überschrieben wird. 

Anbei hab ich mal ein Code Snipped fertig gemacht was zumindest bei mir klappt

Der Code wurde auf zeile 734 - 770 eingefügt

`                              const Prev_Reading = await this.getStateAsync(obj_root + ".Meter_Readings.Current_Reading_W");
                        this.log.debug("Previous_reading from state : " + JSON.stringify(Prev_Reading));
                        if (!Prev_Reading) return;

                        // Get current calculated kWh value, if not present in memory read from states
                        let Prev_calc_reading = 0;
                        this.log.debug("W value from memory : " + JSON.stringify(w_values));
                        this.log.debug("W value from memory_2 : " + JSON.stringify(w_values.calc_reading));
                        if (w_values.calc_reading !== undefined && w_values.calc_reading !== null && (w_values.calc_reading[obj_id] !== undefined && w_values.calc_reading[obj_id] !== null)) {
                                Prev_calc_reading = w_values.calc_reading[obj_id];
                                this.log.debug("Previous_calc_reading from memory : " + JSON.stringify(Prev_calc_reading));

                                // Calculation logic W to kWh
                                calc_reading = Prev_calc_reading + (((reading.ts - Prev_Reading.ts) / 1000) * Prev_Reading.val / 3600000);
                                // Update variable with new value for next calculation cyclus
                                w_values.calc_reading[obj_id] = calc_reading;
                                this.log.debug("New calculated reading : " + JSON.stringify(calc_reading));
                                this.log.debug("new W value from memory : " + JSON.stringify(w_values));

                                // Write values to state
                                await this.setState(obj_root + ".Meter_Readings.Current_Reading", { val: calc_reading.toFixed(3) ,ack: true });
                                await this.setState(obj_root + ".Meter_Readings.Current_Reading_W", { val: reading.val ,ack: true });

                        } else {
                                this.log.debug("Else clause no value in memory present");
                                const temp_reading = await this.getStateAsync(obj_root + ".Meter_Readings.Current_Reading");
                                if (temp_reading !== undefined && temp_reading !== null) {
                                        Prev_calc_reading = parseFloat(temp_reading.val);
                                        if(w_values.calc_reading !== undefined && w_values.calc_reading !== null) {
                                                w_values.calc_reading[obj_id] = Prev_calc_reading;
                                        } else {
                                                w_values.calc_reading = {
                                                        [obj_id]: Prev_calc_reading
                                                };
                                        }
                                        //w_values.obj_id.calc_reading = Prev_calc_reading;
                                        //w_values.calc_reading = {
                                        // [obj_id]: Prev_calc_reading
                                        //};

                                        await this.setState(obj_root + ".Meter_Readings.Current_Reading_W", { val: reading.val ,ack: true });
                                        this.log.debug("Previous_calc_reading from state : " + JSON.stringify(Prev_calc_reading));
                                        this.log.debug("W value from state : " + JSON.stringify(w_values));
                                        return;
                                }
                        }

`
In diesem fall prüft er ob calc_reading bereits vorhanden / und gefüllt ist, wenn ja wird der Wert einfach für die ObjektId gesetzt, wenn nein wird es neu Instanziert. 
Des weiteren waren da bei den getStateAsync obj_id + "..." obwohl in obj_root + "...." geschrieben wird, ich bin jetzt bei iobroker da nicht so firm, ob das so richtig ist, hatte das daher auch angepasst.

**Comment by DutchmanNL** [comment]
danke ! ich habe im moment wenig zeit und deine analyse und code Ansatz hilft sehr !

ich schaue mir das am wochende mal genau an

**Comment by DutchmanNL** [comment]
danke, das war genau die stelle im code (wie man noch an den comments sehen konnte 🤣 ) wo ich aufgehört hatte 🤣 

ich habe deine fix in version 2.3 übernommen, danke dir !

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/744a1709a0ff9c6610b5c3d0c76ed8a3e2d357a5

**Comment by Xoroles** [comment]
Ähm, dass in Zeile 734 der zugriff mit der obj_id statt finden, aber das schrieben in zeile 754 mit obj_root statt findet ist kein Problem? 

Bei meinem Probieren hatte ich ein paar mal Probleme den alten Wert zu lesen. Erst als ich es auf obj_root geändert hatte (oder was anderes) lief es dann endgültig richtig.

**Comment by DutchmanNL** [comment]
> Ähm, dass in Zeile 734 der zugriff mit der obj_id statt finden, aber das schrieben in zeile 754 mit obj_root statt findet ist kein Problem?

nope, beim schreiben habe ich halte den namespace mitgegeben durch obj_root zu verwenden siehe auch die declaration.

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/blob/master/main.js#L641-L642

bij_id waehre in dem fall auch richtig gewesen da es ein setstate und nicht setforeignstate is aber egal :)
