### ISSUE TITLE
Tages Verbrauchs Berechnung Fehlerhaft?

### ISSUE THREAD

**Issue by Xoroles** [iobroker-community-adapters/ioBroker.sourceanalytix#69]
Hallo Zusammen,

Kann es sein das die Werte unter Consumption nicht funktionieren. 
Unter den States sind bei mir aktuell immer nur die Zählerstände der Tage drin. 
Ich würde aber doch die Differenz zwischen den Zählerständen erwarten, sodass ich sehen kann, Am Montag hab ich X kw/h verbraucht und am Dienstag y kw/h. Sehe ich das falsch? Ist das gar nicht angedacht?

**Comment by DutchmanNL** [comment]
Hi,

Was für einen Datenpunkt loggst du ?
Bitte Mal Screenshot vom Datenpunkt und den Werten

Greets Dutch

**Comment by Xoroles** [comment]
Hallo, 
ich denke der Screen zeigt es schon sehr genau

![image](https://user-images.githubusercontent.com/7964052/59872852-f8354c80-939a-11e9-897e-32ee413d3d9c.png)

Im grunde ist es ein auf den Javascript übertragender Wert des aktuellen Stromverbrauchs. 

Wie man sieht, wird als tages wert, immer der Aktuelle gesamt Zählerstand genommen. 
Selbst bei den ausgewärteten Werten direkt auf einem Device, kommt das gleiche Ergebnis raus.

**Comment by DutchmanNL** [comment]
screenshot der Einstellungen ;) (also vom adapter, beide tabs bitte)

**Comment by Xoroles** [comment]
Hi, anbei
![image](https://user-images.githubusercontent.com/7964052/60055710-cbf13700-96de-11e9-948f-fcf5eaf335ac.png)

![image](https://user-images.githubusercontent.com/7964052/60055729-df040700-96de-11e9-85ee-3a2ca9953f91.png)

Anbei noch mal der Datenpunkt welcher gemessen wird.
![image](https://user-images.githubusercontent.com/7964052/60055775-035fe380-96df-11e9-9c4e-54f5c2022489.png)

**Comment by DutchmanNL** [comment]
loggs du einen Wh oder kWh wert ?

**Comment by Xoroles** [comment]
Keins von beiden, hab leider immer nur den Aktuellen W Verbrauch. Das hochrechnen (allgemeiner Zählerstand) klappt ja auch, und sieht soweit plausibel aus

**Comment by DutchmanNL** [comment]
> Keins von beiden, hab leider immer nur den Aktuellen W Verbrauch. Das hochrechnen (allgemeiner Zählerstand) klappt ja auch, und sieht soweit plausibel aus

rechnest du mit deinem script hoch und gibst sourceanalytix nen wH bzw kWh wert oder loggst du den Watt wert ?

**Comment by Xoroles** [comment]
Watt Wert,
hatte ja in einem der vorherigen Tickets die Berechnung schon repariert. So dass diese sauber klappt.

**Comment by DutchmanNL** [comment]
> Watt Wert,
> hatte ja in einem der vorherigen Tickets die Berechnung schon repariert. So dass diese sauber klappt.

jup die Implementierung ist aber leider nog buggy daher werden die Berechnungen nicht richtig übernommen.
ich muss dazu nochmal in ruhe hinsetzen... die zeit :/

**Comment by Xoroles** [comment]
Ja, aber selbst wenn der Wert der da raus kommt falsch ist, er zählt doch zumindest einen zählerstand hoch. Daraus müsste doch nun problemlos die Periodische Werte abgeleitet werden können oder. Sonst gucke ich mir das nochmal an, wenn ich was zeit hab.

**Comment by DutchmanNL** [comment]
bitte Version 0.2.41 probieren

**Comment by Xoroles** [comment]
Probier ich gerne ;)

**Comment by DutchmanNL** [comment]
0.2.41 ist im admin verfügbar und die Funktionalität durch mehrere bestätigt.
ich mach mal zu, wen noch was sein sollte bitte melden :)

**Comment by Xoroles** [comment]
Jo kann ich bestätigen, man muss aber die Punkte anscheinend neu anlegen, erst danach klappte es auch wie es soll.

**Comment by DutchmanNL** [comment]
> Jo kann ich bestätigen, man muss aber die Punkte anscheinend neu anlegen, erst danach klappte es auch wie es soll.

wen man eine Zwischenversion hat ja, da haste recht den die meter readings koennen falsche werte enthalten.

danke fuer die Bestätigung, wir näheren uns dem ende der beta noch 3 features und wir werden auf stable release und ein video + tutorial verfassen
