### ISSUE TITLE
[issue with comma and dot] Startwert für die Analyse

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.sourceanalytix#7]
Ich glaube der Startwert mag keine Komma Werte? 

![screenshot 1579](https://user-images.githubusercontent.com/41079106/51173312-79048f80-18b5-11e9-92d7-d614fece2fd6.png)

**Comment by DutchmanNL** [comment]
is this issue still present in the newest version ? I cannot reproduce it ...
