### ISSUE TITLE
Meter readings empty

### ISSUE THREAD

**Issue by MagicSven81** [iobroker-community-adapters/ioBroker.sourceanalytix#70]
Der Zählerstand wird mir unter
Total_in.consumption.05_current_year
zwar korrekt angezeigt, aber unter:
sourceanalytix.0.sonoff__0__Stromzähler_ED300L__SML_Total_in.Meter_Readings
loggt er die Zählerstände nicht mit.
Eigentlich sollte er dort doch Monatlich, Wöchentlich und täglich den aktuellen Zählerstand festschreiben.
Tut er aber irgendwie nicht.

**Comment by DutchmanNL** [comment]
logst du zufällig einen watt wert ? probier mal bitte version 0.2.41

**Comment by MagicSven81** [comment]
ich logge die kwh Werte meines Zählers.
Einmal den Wert des Strombezugs und einmal den Wert der Stromeinspeisung.
Ist ein 2-Richtungszähler.

Zusätzlich logge ich noch einen reinen Watt Wert und zwar den Wert, den ich aktuell an Watt in meinem Haus verbrauche.
Damit lasse ich mir eine Grafik über 24 Std. anzeigen wie mein Tagesverbrauch war.

Version 0.2.41 ist bereits installiert.

**Comment by DutchmanNL** [comment]
> Edit: Version 0.2.41 installiert - sieht bisher gut aus. Mal schauen ob morgen der Wert aktualisiert wird.

super, wurde inzwischen von mehreren bestätigt sich mach dan hier mal zu. Sollte noch was sein einfach wieder öffnen :)
