### ISSUE TITLE
Darstellung Ordnerstruktur der Datenpunkte

### ISSUE THREAD

**Issue by DanielHD80** [iobroker-community-adapters/ioBroker.sourceanalytix#75]
Mich verwirrt es öfter mal, dass die Ordnerstruktur komisch aufgebaut ist. Unter current year befindet sich this week... Wäre es nicht schöner, das so aufzubauen?

consumption
... current year
...... months
......... 01january
...... weeks
......... 01
... current week
...... 01monday
... 01current day

Ich hoffe es ist klar, wie ich das meine. Wäre von der Logik her glaube ich korrekter! Damit hat man die "langfristigen Protokollierungen" unter current year, die aktuellen Daten aber schneller im Zugriff!

**Comment by DutchmanNL** [comment]
Verstehe was du meinst aber passt nicht ins concept

Den später kommt

Current year
Previous year
Etc

Also die Struktur ist immer das jahr, Dan die Unterverteilung

Es könnte eventuell sinnmachen nicht current year sonder das Jahr selber (also z'n 2019, 2020) zu verwenden

**Comment by DanielHD80** [comment]
Dann würde ich sofort mit Jahreszahlen arbeiten. Das würde dann sicher am meisten Sinn machen...

consumption
... 2019
...... months
......... 01january
...... weeks
......... 01
... 2020
...... months
......... 01january
...... weeks
......... 01
... current week
...... 01 monday
... current day

Just my 2 Cents... ;)

**Comment by DutchmanNL** [comment]
Hmm programmier technisch egal, Frage ist welches Layout ist das beste für die Masse 😉

**Comment by DanielHD80** [comment]
Meine höchst persönliche Meiung: 
- current year, previous year,... Das sind alles sich ändernde Daten
- 2019, 2020,... bleibt immer 2019, 2020,...

**Comment by DutchmanNL** [comment]
Ja ok, aber ich finde dan current und previous nicht übereinstimmt mit Jahren also Inkonsistent.

Dan lieber immer auf Jahr anfangen und darunter die Struktur.

Zusätzlich ein Script für Version Update damit alles von "current year" übertragen wird zum Baum 2019

**Comment by DanielHD80** [comment]
Ja genau so meine ich es... Standard bei einer Neuinstallation wäre dann also

consumption
... 2019
...... months
......... 01january
......... 02 february
......... undsoweiter
...... weeks
......... 01
......... 02
......... undsoweiter
... thisweek
...... 01monday
...... 02tuesday
...... undsoweiter
... 01currentday
... 02currentweek
... 03currentmonth
... 04currentquarter
... 05currentyeas

plus natürlich das gleiche für Kosten

**Comment by DutchmanNL** [comment]
so machen wir's !

**Comment by DutchmanNL** [comment]
ich arbeite gerade an def neuen version fuels nahest Jahr diese Baustelle wird die erste sein um jetzt nach 0.3.0 in den angriff zu nehmen.
Wird also demnaest ne test-version geben

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.

![Schermafbeelding 2020-03-24 om 16 23 23](https://user-images.githubusercontent.com/7318445/78406298-a5174800-7602-11ea-8d81-6fe01e0ad106.png)
