### ISSUE TITLE
"Measurement unit" is ignored

### ISSUE THREAD

**Issue by Omega236** [iobroker-community-adapters/ioBroker.sourceanalytix#82]
Ich habe im Datenpunkt eingestellt er soll "l"  verwenden.

Trotzdem nutzt er die Unit vom DatenPunkt (in meinem Fall Liter).

und dadurch liefert er auch den Fehlerlog:
"Sorry unite type liter not supported yet"

Das gleiche Problem habe ich bei RegenMesser und Sonnenscheindauer, diese konnte ich bis jetzt auch mir Sourceanalytix überwachen. nur kommt nur noch 
"Sorry unite type mm not supported yet"
und
"Sorry unite type min not supported yet"

In 0.2.25 hat noch alles korrekt funktioniert. (wie könnte ich auf diese Version zurück? da es ja nur im Github verfügbar ist)

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.
