### ISSUE TITLE
Öl Einheit m3 unpassend

### ISSUE THREAD

**Issue by Omega236** [iobroker-community-adapters/ioBroker.sourceanalytix#83]
Bei Wasser und Gas ist m3 ja die passende Einheit.

Aber bei Öl ist m3 meiner Meinung nach eher ungebräuchlich.

Dadurch hat man in Allen Auswertungen Bei Tageswerten meist nur Zahlen wie z.B. 0,00132 m3.

Liter als Grundeinheit wäre hier viel besser, so hätte man z.B. Pro Tag 1-50 Liter. Bzw Übers Jahr Typisch 100 - 10000 Liter.

Super wäre wenn man pro DatenPunkt angeben könnte in welcher Einheit es ausgegeben wird.

**Comment by DutchmanNL** [comment]
man kan ab version 0.4.7 selber cost prices und Einheiten definieren :)
