### ISSUE TITLE
Verify Compact mode for your adapter

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.sourceanalytix#93]
We have detected that your adapter supports the compact mode. Please use the latest js-controller 2.0 and verify that everything works.

Some more information what is important to check can be found at ioBroker/ioBroker.js-controller#512 

On questions please answer to the linked issue. Please close this issue after your test and add the version number that you have tested please as a comment.

Thank you for your support.

**Comment by DutchmanNL** [comment]
fixed in upcoming version 0.4.0, please wait for announcement in forum for testing.

In der kommenden Version 0.4.0 behoben, bitte warten Sie auf die Ankündigung im Forum zum Testen.
