### ISSUE TITLE
Autarkie und Eigenverbrauch in % 

### ISSUE THREAD

**Issue by MotschaM** [iobroker-community-adapters/ioBroker.sourceanalytix#94]
Es wäre gut, wenn es eine Funktion geben würde, wenn man noch den Zählerstand der geleisteten Produktion der PV Anlage hinzufügen könnte. 

Dann könnte man die Autarkie und den Eigenverbrauch in Prozent als Datenpunkt schreiben. 
Ich weis nicht wie ich es sonst über Blockly lösen könnte.

**Comment by DutchmanNL** [comment]
ich verstehe nicht genau was du meinst, man kan ja sowohl die Einspeisung als die production mit SOurceAnalytix ermitteln ?

**Comment by DutchmanNL** [comment]
ist die Struktur in 0.4.7 ausreichend ?
