### ISSUE TITLE
Einheit m3 in m³

### ISSUE THREAD

**Issue by Elektroniker0486** [iobroker-community-adapters/ioBroker.sourceanalytix#96]
Einheit in Kubikmeter mit hochgestellter 3 (m³) wird nicht erkannt.

**Comment by DutchmanNL** [comment]
fixed 0.3.0 https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/commit/b3e0ffb1ee5ab6f403ec7b51eb4efff6ba3164bf
